### ISSUE TITLE
A question about building the FTL files

### ISSUE THREAD

**Issue by jpreecenb** [InseeFrLab/keycloakify#10]
Hope you don't mind the question, I wasn't sure where else to ask it.

As part of the "build" process, you are attaching variables on to a global object called `kcContext` (`window.kcContext`).

This is fine and works great.  

As part of my task I have to migrate not only the login related pages, but also account pages as well.  For example, I have an account page that allows the user to change their email address.  Here is the code that links the user to that page;

```
            <@inputs.input id="username" name="username" type="text" value="${(account.email!'')}" class="input_withOption" disabled="true" labelText="Email address" hasOption="true">
                <@buttons.link href="${email.emailPage}" class="inputOption inputOption__link" importance="tertiary" gaId="updateLoginDetails_changeEmailButton">Change</@buttons.link>
            </@inputs.input>
```

We display the email address and provide a "Change" link.  We pre-populate the email address field with the email they used for their account.

The `account` object is provided I believe from Keycloak.  Currently it is not exposed by Keycloakify, even though I assume it is available.

So I was looking at this code;

```
<script>
    Object.deepAssign(
        window.kcContext,
        { "pageId": "login-reset-password.ftl" }
    );
    Object.deepAssign(
        window.kcContext,
         
{
    "realm": {
        "loginWithEmailAllowed": (function (){

            <#attempt>
                return ${realm.loginWithEmailAllowed?c};
            <#recover>
            </#attempt>

        })()
    }
}

    );
</script>
```

Specifically this;

```
            <#attempt>
                return ${realm.loginWithEmailAllowed?c};
            <#recover>
            </#attempt>
```

This is compiled by keycloakfiy.

Is there any way I can easily extend the build process so that I can output my own variables?

**Comment by garronej** [comment]
Hi @jpreecenb,  
Accounts pages are not supported yet.  
This is something that I want to support though but I already mentioned ([see here](https://github.com/InseeFrLab/keycloakify/issues/7#issuecomment-848717987)), we first need a better way to convert `ftl` into `js` it will make implementing missing pages much easier and it will enable users to implement custom pages.  

If you are not afraid to get your hand dirty I can assist you in bringing account support to Keycloakify...

**Comment by jpreecenb** [comment]
@garronej thanks for the response! I'm happy to help out and contribute back to this library, as its heavily relied upon in our project.  I'll probably fork the project, add in the functionality that I need and try and come up with a good generic solution that I can contribute back.

All the best! Great project btw, good work!

**Comment by garronej** [comment]
Do not ￼hesitate to reach me if you need help. I can even introduce the codebase to you on a remote session if it can help.

**Comment by garronej** [comment]
> Is there any way I can easily extend the build process so that I can output my own variables?

Hi @jpreecenb, it is now possible in v2.

**Comment by oha95** [comment]
Hello @garronej, do you have an example of how to redefine the "account" page?

**Comment by garronej** [comment]
Hi @oha95,  
Sorry it's not yet possible.  
Currently only the `login` page can be customised.   

![image](https://user-images.githubusercontent.com/6702424/156215040-88c5b8bb-421d-4d72-bb6b-46cf9e867ad6.png)

**Comment by oha95** [comment]
@garronej, Is this planned for future versions? It would be very interesting.

**Comment by garronej** [comment]
It is not currently scheduled but this is something I would like to get in eventually.  
What is coming next is the support for customising `email`. It's very much possible that it unlock the possibility of customising account at the same time.
