### ISSUE TITLE
Email customization in one .jar along with login 

### ISSUE THREAD

**Issue by hookenful** [InseeFrLab/keycloakify#100]
Hello there!

Trying to implement email customization, but got a bit confused by documentation (https://docs.keycloakify.dev/email-customization). From this, I see, that you create separate theme for email customization, can I work in my already developing login theme? 

For now, for email translations, I just copy email folder with messages and theme.properties manually into my frontend-style-guide folder, but I think I need more native approach, because you've added functional for email customization.

**Comment by hookenful** [comment]
And one more question, is there a chance to rename default name of the theme along with version before build time? Now I am getting frontend-style-guide-keycloak-theme-0.1.0.jar in output as well as name in keycloak admin.

**Comment by garronej** [comment]
>  From this, I see, that you create separate theme for email customization, can I work in my already developing login theme?
Hi,


There is only one theme and one .jar, Keycloak just let you choose what you want to enable.  

> For now, for email translations, I just copy email folder with messages and theme.properties manually into my frontend-style-guide folder, but I think I need more native approach, because you've added functional for email customization.  

I did nothing special for email really. I just provide a convenient way to package the email directory.  
You should be good to go within minutes.  

>  And one more question, is there a chance to rename default name of the theme along with version before build time? Now I am getting frontend-style-guide-keycloak-theme-0.1.0.jar in output as well as name in keycloak admin UI.  

It's based on the `name` field in your package.json

**Comment by hookenful** [comment]
> > From this, I see, that you create separate theme for email customization, can I work in my already developing login theme?
> > Hi,
> 
> There is only one theme and one .jar, Keycloak just let you choose what you want to enable.
> 
> > For now, for email translations, I just copy email folder with messages and theme.properties manually into my frontend-style-guide folder, but I think I need more native approach, because you've added functional for email customization.
> 
> I did nothing special for email really. I just provide a convenient way to package the email directory. You should be good to go within minutes.
> 
> > And one more question, is there a chance to rename default name of the theme along with version before build time? Now I am getting frontend-style-guide-keycloak-theme-0.1.0.jar in output as well as name in keycloak admin UI.
> 
> It's based on the `name` field in your package.json

Thanks for your help :)

One more question, is it possible to transform username input? I am using mobile phone as username, and I am storing it with 8xxxxx format, but sometimes users can write +7xxxxx, but I need it to be transformed to 8xxxxx format. How to achieve that ?

**Comment by garronej** [comment]
You mean while user register?

**Comment by hookenful** [comment]
> You mean while user register?

No, while login.

**Comment by garronej** [comment]
Yes, this is really a easy feature to implement with Keycloakify.  

You'll have to opt the customization at the component level. [Get started with this setup](https://github.com/garronej/keycloakify-demo-app/tree/look_and_feel).  
Then you could use a library [like this one](https://github.com/react-hook-form/react-hook-form) to perform field validation.  

Good luck.

**Comment by hookenful** [comment]
How can I add translations into email messages.properties?

**Comment by garronej** [comment]
Just have a look at the content of the `keycloak_email` directory.  
You'll understand what you deed to change  

https://docs.keycloakify.dev/email-customization

**Comment by hookenful** [comment]
Is it enough to generate **keycloak_email** directory? After that In every generated .jar I will have email directory and in theme.properties in themes array: ["login", "email"]? If yes, thats nice!

**Comment by garronej** [comment]
Yes that's exactly it.  

You just have to run `npx create-keycloak-email-directory` once
