### ISSUE TITLE
Add support for 2FA setup page

### ISSUE THREAD

**Issue by tylucaskelley** [InseeFrLab/keycloakify#102]
I was working on customizing the theme for the `LoginOtp` page, and found that the other side of the 2FA support - the initial setup page (screenshot below) doesn't seem to be supported in this library. Is there a plan to add support for it?

![image](https://user-images.githubusercontent.com/5448759/167020394-fdd7a920-cb10-43a1-aa32-02aa935120bf.png)

**Comment by garronej** [comment]
Hi, @tylucaskelley 

I just added [a documentation section](https://docs.keycloakify.dev/limitations#some-pages-still-have-the-default-theme.-why) for you.  

Best regard
