### ISSUE TITLE
cache zip

### ISSUE THREAD

**Issue by aikin-vip** [InseeFrLab/keycloakify#103]
can we cached zip file?  when i built in local. run  yarn  keycloak ,  command will download zip file again and again.

**Comment by garronej** [comment]
Hi @aikin-vip,  
Yes this is something that I have considered at first but I didn't implement. Cost of opportunity.  
If you want to submit a PR for this however I will happily review and merge it!  

What trouble me though is when you say *over and over again*.  
Are you aware that you can [debug your theme outside of Keycloak](https://docs.keycloakify.dev/developpement#seeing-the-result-live)?  
I personally only build the theme on my dev machine before we upgrade our Keycloak server to a new major version.  
The rest of the time, it is build in [the CI pipeline](https://github.com/garronej/keycloakify-demo-app/blob/9695834ddecf2fa19c65c8e2f28fb7b3d4b581ec/.github/workflows/ci.yaml#L23).

**Comment by aikin-vip** [comment]
Hi @garronej  
Thank you for your patient explanation and answer, i will try to submit a pr.
I know I can debug the theme locally, but because of my development environment, I need to run Yarn Keyclay many times in the local area.

**Comment by janLindner** [comment]
Hi @aikin-vip, 
are you already working on a PR regarding this issue? Otherwise, I would have a look at it myself too, as I am currently facing similar issues as yourself and would love to have this feature, to enhance development time.

**Comment by garronej** [comment]
There is now a caching mechanism in Keycloakify v6 (`6.0.0-beta.13`)
