### ISSUE TITLE
[Question] Theme file size

### ISSUE THREAD

**Issue by kamilbonna** [InseeFrLab/keycloakify#104]
Hello, 

Thanks for your package! I've successfully built custom theme using `keycloakify`, but the archived theme file is quite large - it has ~60MB. I inspected file sizes within my theme directory and it turns out that over 40MB comes from these two node modules:
- `.../resources/resources_common/node_modules/patternfly`
- `.../resources/resources_common/node_modules/rcues`
I can see that most of the file size for these modules results from various font files. I'm just curious if this is unavoidable or can those be removed without affecting the theme?

**Comment by garronej** [comment]
Hi @kamilbonna,  
Thanks for the nice feedback.  
Those packages are dependencies of the base Keycloak theme.  
I didn't add them, the core Keycloak theme did.  
The goal it that, before customisation, that the theme generated be more or less identical to the builtin Keycloak theme of Keycloak v11.0.3.  

Two questions:  
1) Is the size of the theme a problem in your use case? Rest assured that it won't impact the end user experience in any way.  
2) We are building a pretty big app and [our bundle size ends up being 16MB](https://github.com/InseeFrLab/onyxia-web/releases/tag/v0.54.1)...

**Comment by kamilbonna** [comment]
@garronej thanks for these explanations.

1. It's not a problem, specifically if it has no impact on the end user. I was just curious why a few simple static sites end up being a ~60 MB file. 
2. Thanks, I will look into it for a reference.

**Comment by garronej** [comment]
There's been work done on this front.  
The generated .jar should be at least 10 time smaller, only used assets are included in the .jar now.  
We tell at build time what are the resources actually used.
