### ISSUE TITLE
Phantom strange error "An error has occurred when reading existing sub-variable "loginAction"

### ISSUE THREAD

**Issue by hookenful** [InseeFrLab/keycloakify#105]
Hello there!

Sometimes, we are getting some strange error during "UPDATE_PASSWORD" action with default text and in logs there are such messages: 

![image](https://user-images.githubusercontent.com/31849464/169349206-8254af7c-dc6f-42ee-a2ec-29f6f30d37ba.png)

We are using keycloakify. Do you have any thoughts on that?

**Comment by garronej** [comment]
Hi @hookenful,  
Thanks for reporting,  
Those errors can be easily fixed, I just need some good soul like you to report them when they arise.  🙂  
What I need is, on the pages that generates the error, the code that generate the `kcContext`:  
You would obtain it like this:

https://user-images.githubusercontent.com/6702424/169353165-8d2ea0e2-5f5d-4ef5-aee4-2e07963d430a.mov

If you can copy and past it here, I can release a patch.  

Anyway, that error is just noise, they can be safely ignored, but it's annoying noise.

**Comment by hookenful** [comment]
> 

Thank for your fast reply. Do I need to catch code from page only during error or anytime?

**Comment by hookenful** [comment]
> Thank you! Seem like this error have been fixed already [c583b83](https://github.com/InseeFrLab/keycloakify/commit/c583b83cbb730e47de71dea0d00c1e4ed287167b) Try updating keycloakify, the issue should be gone.
> 
> > How are you going to fix this?
> 
> With <img alt="image" width="586" src="https://user-images.githubusercontent.com/6702424/169358123-5966857d-c2b3-4362-951b-f8ba8e3dfd05.png">
> 
> I can see that trying to dereference url.loginAction on the error.ftl page makes Java throw.

What is this version where that was fixed?

**Comment by garronej** [comment]
It was fixed in version 4.8.5 but you should update to v5.  
There is no major breaking changes.
