### ISSUE TITLE
Cannot find module useKcMessage

### ISSUE THREAD

**Issue by hookenful** [InseeFrLab/keycloakify#106]
Hey again,

After update I am having that error:

![image](https://user-images.githubusercontent.com/31849464/169371752-e5a7c7ee-5fed-4db6-9aa7-f64430d3e0d3.png)

I have executed: yarn install command already

**Comment by hookenful** [comment]
Should I use kcMessages and select appropriate?

**Comment by garronej** [comment]
Sorry it has been renamed,  
It's no longer `useKcMessage` but `getMsg` and it's no longer a hook.  
https://github.com/garronej/keycloakify-demo-app/blob/9b0cc8dbcb0f13552c397893ea01a834717c468e/src/KcApp/Register.tsx#L4
https://github.com/garronej/keycloakify-demo-app/blob/9b0cc8dbcb0f13552c397893ea01a834717c468e/src/KcApp/Register.tsx#L26
