### ISSUE TITLE
kcMessagesExtension doesn't overwrite default messages

### ISSUE THREAD

**Issue by hookenful** [InseeFrLab/keycloakify#107]
Hi there,

 I am trying to override default translation messge by this:

```ts
import { kcMessages } from 'keycloakify';

Object.assign(kcMessages.ru, {
  invalidPasswordHistoryMessage: 'Некорректный пароль: пароль не должен совпадать с предыдущим.',
});
```

Then importing this `kcMessagesExtension.ts`  into `Index.tsx`:

`import './utils/kcMessagesExtension';`

But anyway I have default message translation. What did I miss?

Thanks in advance

**Comment by garronej** [comment]
Hi @hookenful,  
There is nothing wrong in what you showed me, it should work.  
I'll need more information to help you.  
Ideally a repo.
