### ISSUE TITLE
Typed example for getMsg() function

### ISSUE THREAD

**Issue by hookenful** [InseeFrLab/keycloakify#108]
Hi there, I am trying to adopt new `getMsg()` function, but es lint has troubles with it, because it is not typed and returns `any`.
![image](https://user-images.githubusercontent.com/31849464/169487747-30dca9e7-3736-4648-9657-35ddcc052102.png)

Do you have any samples with typed return object?

Thanks in advance!

**Comment by hookenful** [comment]
Got fixed it with defining return type for `getMsg()` func

```

export type GetMsgFunctionType = {
  msgStr: (key: MessageKey, ...args: (string | undefined)[]) => string;
  msg: (key: MessageKey, ...args: (string | undefined)[]) => JSX.Element;
};
```

And using like that, does it appropriate?   
`  const { msg } = getMsg(kcContext) as GetMsgFunctionType;`

**Comment by garronej** [comment]
Hi @hookenful,  
There must be something wrong in your project's configuration.  
`getMsg` is very strictly typed.  

https://user-images.githubusercontent.com/6702424/169513827-52fd1088-a8b4-4861-aebf-c06fe8efde83.mov
