### ISSUE TITLE
Again phantom error after update to v5.3.2

### ISSUE THREAD

**Issue by hookenful** [InseeFrLab/keycloakify#109]
Hi there!

Getting again that strange problem while activating update-password link from email:
![image](https://user-images.githubusercontent.com/31849464/169783550-5b3fa747-7552-4c97-8331-1eb380503469.png)

Source code of error page:
https://pastebin.com/TxQPpR4x

Thank for any help!

**Comment by garronej** [comment]
Hi @hookenful,  

Thanks for the snippet, unfortunately you copy pasted to me the code of the `error.ftl` page, there isn't anything on the page you sent be that makes Keycloak throw.  

The error is on the `info.ftl` page.

**Comment by hookenful** [comment]
https://pastebin.com/YRFgT3eN Is that `info.ftl` page? Maybe you mean that one that we are skipping.

**Comment by garronej** [comment]
Yes it's the one you are skipping.

**Comment by hookenful** [comment]
Look at our `KcApp` . Maybe we missed something? https://pastebin.com/GBDKBkJF 

How can I get there meaning that we are skipping it?

**Comment by hookenful** [comment]
`import React, { useLayoutEffect } from 'react';

import { KcFormLogin } from 'components/Keycloack/KcFormLogin';
import { KcFormPage } from 'components/Keycloack/KcFormPage';
import { KcFormResetPassword } from 'components/Keycloack/KcFormResetPassword';
import { KcContextBase } from 'keycloakify';
import { KcApp as KcAppBase } from 'keycloakify/lib/components/KcApp';

import { KcFormUpdatePassword } from './KcFormUpdatePassword';

import type { KcProps } from 'KcTypes/kcProps';

export const KcApp = React.memo(({ kcContext, ...props }: { kcContext: KcContextBase } & KcProps) => {
  useLayoutEffect(() => {
    if (kcContext.pageId === 'info.ftl' && kcContext.actionUri !== undefined) {
      window.location.href = kcContext.actionUri;
    }
  }, [kcContext.pageId]);

  switch (kcContext.pageId) {
    case 'login.ftl':
      return <KcFormLogin {...{ kcContext: kcContext as KcContextBase.Login & KcProps, ...props }} />;
    case 'login-page-expired.ftl':
      return <KcFormPage {...{ kcContext: kcContext as KcContextBase.LoginPageExpired & KcProps, ...props }} />;
    case 'login-reset-password.ftl':
      return (
        <KcFormResetPassword {...{ kcContext: kcContext as KcContextBase.LoginResetPassword & KcProps, ...props }} />
      );
    case 'login-update-password.ftl':
      return (
        <KcFormUpdatePassword {...{ kcContext: kcContext as KcContextBase.LoginUpdatePassword & KcProps, ...props }} />
      );
    default:
      return <KcAppBase {...{ kcContext, ...props }} />;
  }
});
`

**Comment by garronej** [comment]
There isn't anything that you can do on your end to prevent this error, ony sollution is to give me the HTML code of the page `info.ftl`.  

You have two option:  
1) Try to play with the chrome debugger to pause before redirecting: https://gist.github.com/carcinocron/f6a509b84fe82a718816  
2) Comment out `window.location.href = kcContext.actionUri;` just time to copy the page and past it to me.

**Comment by hookenful** [comment]
I suppose this one is Info.ftl: https://pastebin.com/DTwRdPwZ

**Comment by garronej** [comment]
> https://pastebin.com/DTwRdPwZ  

The link is dead

**Comment by hookenful** [comment]
Sorry, here it is https://gist.github.com/hookenful/0de16d7325f0002663550ee7697bcbb6

**Comment by garronej** [comment]
Hi @hookenful, thank you for your contribution,  
It should be fixed 5.4.0.  
Do you confirm?

**Comment by hookenful** [comment]
> Hi @hookenful, thank you for your contribution, It should be fixed 5.4.0. Do you confirm?

Thanks for your effort, I need to deploy on swarm and then I'll reply for that, ok?

**Comment by garronej** [comment]
@hookenful You are welcome,  

> Is it possible to prevent blinking? I should define an empty KcInfo then?  

This should do it:  
```diff
import React, { useLayoutEffect } from 'react';

import { KcFormLogin } from 'components/Keycloack/KcFormLogin';
import { KcFormPage } from 'components/Keycloack/KcFormPage';
import { KcFormResetPassword } from 'components/Keycloack/KcFormResetPassword';
import { KcContextBase } from 'keycloakify';
import { KcApp as KcAppBase } from 'keycloakify/lib/components/KcApp';

import { KcFormUpdatePassword } from './KcFormUpdatePassword';

import type { KcProps } from 'KcTypes/kcProps';

export const KcApp = React.memo(({ kcContext, ...props }: { kcContext: KcContextBase } & KcProps) => {
  useLayoutEffect(() => {
    if (kcContext.pageId === 'info.ftl' && kcContext.actionUri !== undefined) {
      window.location.href = kcContext.actionUri;
    }
  }, [kcContext.pageId]);

  switch (kcContext.pageId) {
+  case 'info.ftl':
+    return null;
    case 'login.ftl':
      return <KcFormLogin {...{ kcContext: kcContext as KcContextBase.Login & KcProps, ...props }} />;
    case 'login-page-expired.ftl':
      return <KcFormPage {...{ kcContext: kcContext as KcContextBase.LoginPageExpired & KcProps, ...props }} />;
    case 'login-reset-password.ftl':
      return (
        <KcFormResetPassword {...{ kcContext: kcContext as KcContextBase.LoginResetPassword & KcProps, ...props }} />
      );
    case 'login-update-password.ftl':
      return (
        <KcFormUpdatePassword {...{ kcContext: kcContext as KcContextBase.LoginUpdatePassword & KcProps, ...props }} />
      );
    default:
      return <KcAppBase {...{ kcContext, ...props }} />;
  }
});

```

**Comment by hookenful** [comment]
> This should do it:

Worked like a charm, very thankful :) Cya, have a nice evening, Joseph.
