### ISSUE TITLE
Accessing social variable from context outside the Login page

### ISSUE THREAD

**Issue by SunriseM** [InseeFrLab/keycloakify#11]
Hey, I want to add "Sign Up with {social display name}" buttons in my register page, but apparently it's not possible to access the `social` variable outside the login page.

After checking the code, I guess it's because it's missing this part in the `generateFtl/register.ftl` file:

```ftl
 "social": { ... },
```

Is there already a workaround for this?

If not, one idea I have, is to build the generateFtl files programmatically, where we define the variables based on the config or the default value. For example (The code is just so the idea can be better understood) : 

```ts
//foo/variables
export const url = `{
        "loginResetCredentialsUrl": (function (){
            <#attempt>
                return "${url.loginResetCredentialsUrl?no_esc}";
            <#recover>
            </#attempt>
        })(),
        "registrationUrl": (function (){
            <#attempt>
                return "${url.registrationUrl?no_esc}";
            <#recover>
            </#attempt>
        })()
}`

export const realm = `{
        "loginWithEmailAllowed": (function(){
            <#attempt>
                return ${realm.loginWithEmailAllowed?c};
            <#recover>
            </#attempt>
        })(),
        "rememberMe": (function (){
            <#attempt>
                return ${realm.rememberMe?c};
            <#recover>
            </#attempt>
        })(),
        "password": (function (){
            <#attempt>
                return ${realm.password?c};
            <#recover>
            </#attempt>
        })(),
        "resetPasswordAllowed": (function (){
            <#attempt>
                return ${realm.resetPasswordAllowed?c};
            <#recover>
            </#attempt>
        })(),
        "registrationAllowed": (function (){
            <#attempt>
                return ${realm.registrationAllowed?c};
            <#recover>
            </#attempt>
        })()
}`
// ...
```

```ts
import * as variables from 'foo/variables'
import * as config from 'foo/config'

const defaultVariables = {
	login: ["url", "realm", ...],
	...
}

const generateFile = (name: string) => {
	const fileVariables = config.variables?.[name] || defaultVariables[name]
	
	const entries = fileVariables.map(variable => {
		return [variable, variables[variable]]
	}

	const file = `
		<script>
			const _= ${JSON.stringify(Object.fromEntries(entries))} 
		</script>
	`
	
	// write file
}
```

Then in a config file we could easily add or remove the variables we need

```ts
{
	variables: {
		register: ["url", "realm", ..., "social"]
	}
}
```

I don't know much about how the lib works, so I hope this helps to find a way to solve this problem.

**Comment by garronej** [comment]
Sorry I am in the rush. I don't have the time to review this issue right now.  
I will get back to it later but just know that we are implementing it ourselves right now so it should work.  
![image](https://user-images.githubusercontent.com/6702424/122054199-bf90a800-cde7-11eb-8208-bb87e8345aed.png)

**Comment by SunriseM** [comment]
No problem.

Yeah, in the login page it works fine, but I want to have that button (AgentConnect or any other social identifier being used) in the register page too.

**Comment by garronej** [comment]
Ok I see, it's a quick fix assuming that Keycloak do provides the social object on the `register.ftl` page witch is not certain given that they don't display the identity providers on the register page.  
Also you will have to edit the structure of the register template so it shows the providers. You won't be able to customize using CSS only.

**Comment by garronej** [comment]
@SunriseM that's it, install the latest version you should have `kcContext.social` on the register page. Let me know if it works

**Comment by SunriseM** [comment]
Thank you, it worked fine. closing
