### ISSUE TITLE
npx create-keycloak-email-directory failed with 404

### ISSUE THREAD

**Issue by Xapgkop4uk** [InseeFrLab/keycloakify#110]
Hi, there!

I tried to create a theme for emails by following https://docs.keycloakify.dev/email-customization.

GET https://registry.npmjs.org/create-keycloak-email-directory returns 404 (not found)

```
npm -v
8.10.0
```

Please, help me to resolve that issue.

**Comment by Xapgkop4uk** [comment]
As a workaround works:
`node node_modules/keycloakify/bin/create-keycloak-email-directory.js`

**Comment by garronej** [comment]
Hey @Xapgkop4uk,  
Thanks for reporting,  
Does it do it after a clean dependency install?  
What package manager CLI are you using? `npm`, `yarn 1.X`, `pnpm`... ?

**Comment by Xapgkop4uk** [comment]
I guess npx script should work without any dependencies.
And npx is a npm 😃

**Comment by garronej** [comment]
I mean what package manager do you use to install your dependencies?  
At the root of your project do you have a `.yarn.lock` file, a `package-lock.json`...?

**Comment by Xapgkop4uk** [comment]
I use yarn

**Comment by garronej** [comment]
yarn 1.X or yarn 2 (Berry) ?

**Comment by Xapgkop4uk** [comment]
yarn -v
1.22.10

**Comment by garronej** [comment]
I don't know what caused the issue but I can't reproduce neither on mac or linux.   
I think if you reinstall your depencencies from scratch it should work.  

Thanks for reporting

**Comment by erikdstock** [comment]
Happened to me too, yarn and npx both.

**Comment by garronej** [comment]
Hi @erikdstock,  

For `npx create-keycloak-email-directory` to work you must be at the root of your project and have `keycloakify` installed.  
What version of Keycloakify are you using?  
https://github.com/InseeFrLab/keycloakify/blob/23f6c7db00ece3dfdfa8d0108e50d3da32847e9a/package.json%23L26
