### ISSUE TITLE
Random strage "wrong credentials message" during UPDATE_PASSWORD action from email in 5.4.0

### ISSUE THREAD

**Issue by hookenful** [InseeFrLab/keycloakify#111]
Hello ! 

Hope you doing well, Joseph.

Although blinking problem was gone with proper `Info.tsx` handling returning null, we are still getting random error when performing click from update password email and are stuck on the wrong credentials screen without nav buttons.

![image](https://user-images.githubusercontent.com/31849464/170863347-863289ac-c9a4-43f4-98e9-e049b768620e.png)

https://gist.github.com/hookenful/878db28ba95186961694ad2ee770107d

```

2022-05-29 17:29:58 | ----
-- | --
  |   | 2022-05-29 17:29:58 | - Reached through: ${ftl_object_to_js_code_declaring_an_...  [in template "error.ftl" at line 7, column 1]
  |   | 2022-05-29 17:29:58 | - Failed at: #if !object[key]??  [in template "error.ftl" in function "ftl_object_to_js_code_declaring_an_object" at line 187, column 21]
  |   | 2022-05-29 17:29:58 | FTL stack trace ("~" means nesting-related):
  |   | 2022-05-29 17:29:58 | ----
  |   | 2022-05-29 17:29:58 | 2022-05-29 14:29:58,114 ERROR [freemarker.runtime] (executor-thread-246) Error executing FreeMarker template part in the #attempt block: freemarker.core._TemplateModelException: An error has occurred when reading existing sub-variable "resetCredentialsFlow"; see cause exception! The type of the containing value was: extended_hash+string (org.keycloak.models.jpa.RealmAdapter wrapped into f.e.b.StringModel)
  |   | 2022-05-29 17:29:57 | ... 150 more
  |   | 2022-05-29 17:29:57 | at org.hibernate.internal.SessionImpl.find(SessionImpl.java:3395)
  |   | 2022-05-29 17:29:57 | at org.hibernate.internal.SessionImpl$IdentifierLoadAccessImpl.load(SessionImpl.java:2807)
  |   | 2022-05-29 17:29:57 | at org.hibernate.internal.SessionImpl$IdentifierLoadAccessImpl.perform(SessionImpl.java:2763)
  |   | 2022-05-29 17:29:57 | at org.hibernate.internal.SessionImpl$IdentifierLoadAccessImpl.lambda$load$1(SessionImpl.java:2807)

```

It fixes with sending another email, but seems strange behavior. I can provide more info for debug, just ask for it. 

Thanks in advance !

**Comment by garronej** [comment]
Hi @hookenful,  

> it seems strange behavior.  

Could you try with the default theme, see if you get the same behaviour, if you don't, could you describe to me how it differs?  

> Failed at: #if !object[key]??  

Regarding this error, I'd be happy to provide a patch but it seems that the gist you attached is not the pages that generates the error.  

Here is where the error appends according to the log: https://github.com/InseeFrLab/keycloakify/blob/5140389502fb99b985fb6245c62ab1977d875d0b/src/bin/build-keycloak-theme/generateFtl/ftl_object_to_js_code_declaring_an_object.ftl#L185-L192   

I should see somewhere in the gist `/*Couldn't test if XXXX is available on this object*/`

**Comment by hookenful** [comment]
Hi !

I've checked with default theme and the problem persists there too.

I've figured that that problem is with our backend, we are creating user in some kind chain of routing slip activities and when one fail, others are compensating themselves, but the email with token was already sent. So that there is obvious that it is saying about wrong credentials, because account is deleted by the time.
