### ISSUE TITLE
White blank page after password update action page

### ISSUE THREAD

**Issue by hookenful** [InseeFrLab/keycloakify#114]
Hi there ! 
 
I am having strange white page instead of page with text and button to proceed to my website page. 

![image](https://user-images.githubusercontent.com/31849464/171675145-82eb40bc-9e12-4557-afd9-e3333552ad54.png)

Here is the code for page before white blank page - the page with passsword setting : https://gist.github.com/hookenful/a454ce48d1b22f95cfbe73a58b01e91a

And it is the code of blank page: https://gist.github.com/hookenful/172626bc633f01cf14dd4c8b18d1a543

What can be wrong? 

Thanks in advance for any help :)

**Comment by hookenful** [comment]
I have such `KcApp`

```
export const KcApp = React.memo(({ kcContext, ...props }: { kcContext: KcContextBase } & KcProps) => {
  useLayoutEffect(() => {
    if (kcContext.pageId === 'info.ftl' && kcContext.actionUri !== undefined) {
      window.location.href = kcContext.actionUri;
    }
  }, [kcContext.pageId]);

  switch (kcContext.pageId) {
    case 'info.ftl':
      return null;
...
```

and `KcFormUpdatePassword` - https://gist.github.com/hookenful/f11eae3480f2c2d040e40b048f71341c

**Comment by hookenful** [comment]
I've found one of the versions of theme from v4.3.2 and I report that here missing page is visible.

Gonna provide MVP soon, very strange bug..
![image](https://user-images.githubusercontent.com/31849464/171873975-4fa28df6-7b5b-4c0b-896d-c8bc85b5f44f.png)

**Comment by hookenful** [comment]
What is `skipLink` one of a props in Info?

**Comment by garronej** [comment]
@hookenful sorry I didn't find the time to deal with this issue before.  
Did you solve it already or do you still have problems?

**Comment by hookenful** [comment]
But I have another, not related question. 
I need to customize email template translations and their subjects. Can you provide, please a reproducable sample how can I do it  without manual modifying messages_ru.properties?

**Comment by garronej** [comment]
@hookenful,  
Well you could directly edit the template if you only need Russian:  
<img width="1218" alt="image" src="https://user-images.githubusercontent.com/6702424/172652695-b642240a-f92d-4581-b44f-0dede04a7809.png">

But you are kind of expected to edit the `messages_ru.properties`  

<img width="1727" alt="image" src="https://user-images.githubusercontent.com/6702424/172652908-5e8b6e7d-a8a3-4919-862f-01e56c716b0e.png">

But are you aware of this:  https://docs.keycloakify.dev/email-customization  
Have you run the `npx create-keycloak-email-directory` that creates the `keycloak_email` directory?

**Comment by hookenful** [comment]
Yes, I've run this command and I already have `keycloak_email` folder. 
So I need to modify messages_xx.properties and then build .jar theme?

**Comment by hookenful** [comment]
Can I pass user email or username to the email?

**Comment by garronej** [comment]
> Yes, I've run this command and I already have keycloak_email folder.
> So I need to modify messages_xx.properties and then build .jar theme?   

Yes, the email theme will be included in the bundle.  

> Can I pass user email or username to the email text?  

Good question! There must be informations in the FreeMarker context.  I will try to get a JSON with all the available data tomorrow and if there is I'll show you how to read the info.

**Comment by hookenful** [comment]
I've figured it with adding to executeActions.ftl to one of parameters function `user.getUsername()` and it worked. But I haven't really figured how magically arguments indexes and their position are here.

```
${kcSanitize(msg("executeActionsBodyHtml",link, linkExpiration, user.getUsername(), requiredActionsText, linkExpirationFormatter(linkExpiration)))?no_esc} 
```
Username here is somehow  equals for {2} in arguments, and link is {0}.  But what about first string quoted argument ? Seems strange for me..

**Comment by garronej** [comment]
`"executeActionsBodyHtml"` ?   
It's the key that you'll find in your `messages_xx.properties`:  

<img width="1144" alt="image" src="https://user-images.githubusercontent.com/6702424/172677369-2ced6bf1-60aa-4c92-afac-f16eaadca5c2.png">

{2} will be replaced by the username.  

It's classic i18n.  

PS: By the way I just published a new i18n library: https://www.i18nifty.dev

**Comment by garronej** [comment]
Thank you for the feedback @hookenful,  I'm happy everything works as expected now.  
And congrats on becoming full stack ^^  

Hey, if I dare to ask.  Would you recommend me for [this GitHub program](https://stars.github.com/nominate/)?
