### ISSUE TITLE
Node.js 16 node-gyp build error

### ISSUE THREAD

**Issue by janos-hidvegi-mbh** [InseeFrLab/keycloakify#116]
When installing packages with `yarn` I get a build error on Node.js 16.
It works fine with Node.js 14

I'm using MacOS with an M1 mac.

```
/Users/jani/Library/Caches/node-gyp/16.15.1/include/node/v8-internal.h:492:38: error: no template named 'remove_cv_t' in namespace 'std'; did you mean 'remove_cv'?
            !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
```

**Comment by garronej** [comment]
Hi @janos-hidvegi-mbh what do you mean by "installing packages" ?

**Comment by janos-hidvegi-mbh** [comment]
Hi!

I mean running `yarn install`

**Comment by garronej** [comment]
There isn't any dependencies in Keycloakify that requires to be compiled against a specific version of node.  

I think your problem must be related to another dependency like `node-sass`.

**Comment by janos-hidvegi-mbh** [comment]
Ohh, sorry, I wasn't clear enough.
I got the error, when I tried to set up the https://github.com/garronej/keycloakify-demo-app repo.

This is what I did:
1. I used the [keycloakify-demo-app](https://github.com/garronej/keycloakify-demo-app) as a template.
2. I cloned it
3. I ran `yarn install`, that threw the error

**Comment by garronej** [comment]
Ok, thanks for reporting!

I updated `node-sass` it works with node16 and M1 mac.  
That said, I include `node-sass` in the demo project just because I know many peoples use `scss` but I personally don't recommend it, we use [`tss-react`](https://www.tss-react.dev) for styling.
