### ISSUE TITLE
Add email value in forgot email message pop up

### ISSUE THREAD

**Issue by hookenful** [InseeFrLab/keycloakify#118]
Hi there

I am already awared of modifying emails , but there is a theme which is still unclear for me with keycloakify. I need to modify pop up for forgotten password form, I suppose I need do the same .ftl trick, but what for template? 
Where are `messages.xx.properties` located?

![image](https://user-images.githubusercontent.com/31849464/173185540-95ea1370-8aa3-428b-a44f-874cbce08099.png)

**Comment by garronej** [comment]
https://app.gitbook.com/o/-MKqst3DGo-JnGfa6Ewt/s/0HOOrw5vuMQw6UmxALOh/adding-text-keys

**Comment by hookenful** [comment]
> https://app.gitbook.com/o/-MKqst3DGo-JnGfa6Ewt/s/0HOOrw5vuMQw6UmxALOh/adding-text-keys

![image](https://user-images.githubusercontent.com/31849464/173223363-9910e0c6-b1bd-4f12-9d37-931ca95c6835.png)

I am using this account

**Comment by hookenful** [comment]
> https://app.gitbook.com/o/-MKqst3DGo-JnGfa6Ewt/s/0HOOrw5vuMQw6UmxALOh/adding-text-keys

Thanks, I've already seen it. But I need one more thing that is not covered. I need to pass "user.getEmail()" into somewhere in .ftl file.

**Comment by garronej** [comment]
Hi @hookenful,  
Ok, i'll have a look later today

**Comment by garronej** [comment]
sorry I forgot, reopen in discussion if you still need help
