### ISSUE TITLE
kcContext.auth no longer being set correctly

### ISSUE THREAD

**Issue by bplotnick** [InseeFrLab/keycloakify#121]
Typically `kcContext.auth` contains fields like `showTryAnotherWayLink`, which allows users to pick auth methods. However, as of v5.0.0, this is no longer working as `kcContext.auth` is being set as `false`.

This is easily reproducible - 1) directly observe the value or 2) try with multiple auth methods - the built-in theme will have the link but the keycloakify theme will not.

I've narrowed this down to starting in v5.0.0, but i haven't been able to determine why it is happening.

**Comment by garronej** [comment]
Hi,  
Thank you for reaching out.  
I haven't investigate in depth yet but are you sure it's related to Keycloakify?  
At first sight it looks like kcContext.auth is actually false (whatever it means).   
Can you give me a version ok Keycloakify where it was working. (The bump to v5 can't be it. It's a refactor of i18n) Also can you give me the version of Keakcloak you are running?

**Comment by garronej** [comment]
Thank you for reporting, there is indeed an error on keycloakify's side.  
I doubt it's the bump to v5 that causes it though....

**Comment by bplotnick** [comment]
I thought so too given the fact that it was just i18n, but I bisected the
releases and v5.0.0 was the first release that had this bug.

**Comment by garronej** [comment]
I found the gulty commit.  
It's the bump from 5.3.2 -> 5.4.0

**Comment by garronej** [comment]
@bplotnick it's fixed in latest release,  
Thanks for reporting!

**Comment by bplotnick** [comment]
I must've messed up my bisect somehow. Glad you tracked down the issue. I've confirmed that I can't repro the issue anymore. Thanks @garronej!
