### ISSUE TITLE
No assets loaded?

### ISSUE THREAD

**Issue by Elegant996** [InseeFrLab/keycloakify#126]
When attempting to use react projects such as [this](https://github.com/jesec/flood), the login page does not appear to load any assets. A symlink was created to have `build -> dist/assets` where everything is located but when loading the `.jar` in `docker` per the instructions for testing, nothing appears.

Reverting the theme back to `keycloak` does load the original theme but it's unclear why the generated `.jar` theme does not appear.

**Comment by garronej** [comment]
Hi @Elegant996,  
Have you make sure your app is matching [the requirements](https://docs.keycloakify.dev/#supported-react-frameworks) to integrate with Keycloakify.  
If you don't think you can adapt it, I suggest you make your Keycloakify theme a standalone project.  

Best regards,
