### ISSUE TITLE
Issue generating proper kcContext values in auth property

### ISSUE THREAD

**Issue by bardius** [InseeFrLab/keycloakify#130]
Since commit https://github.com/InseeFrLab/keycloakify/commit/9de0083ca67fd35c29a6c4b93d113b8705c72da8 the kcContext.auth object is broken and does not contain all properties that it used to. One example is the authenticationSelections that are required if you want to have flows with alternative executions and allow user to select the desired one.

This is due to a wrong equality check at method **are_same_path** of file **ftl_object_to_js_code_declaring_an_object.ftl** that makes all comparizons that have more that one items in the search array to fail.

```ftl
<#if path?size != path?size> 
```

should become:

```ftl
<#if path?size != searchedPath?size>
```

Thank you for the great effort!

**Comment by garronej** [comment]
@bardius,  
Good catch thanks!  

Do you want to issue a PR? I'd merge it straight away.
