### ISSUE TITLE
Can't run npx create-keycloak-email-directory for keycloak version 16.1.1 - [object Object] instead of required action name on email

### ISSUE THREAD

**Issue by clementinedeb** [InseeFrLab/keycloakify#134]
Hello,

First of all, thanks for your work, it really helped me to quickly and easily customize the login page :)

To give some context:
I needed to slightly change the theme of the login and email Keycloak pages for my app, so I forked the demo app and followed the documentation's instruction. I adapted the css and now the pages looks exactly as I wanted, the problem is not there.

The keycloak I'm using is in 16.1.1 version.
When I try to run  `npx create-keycloak-email-directory` for this keycloak version, I get the following error:

![Capture d’écran 2022-07-11 à 17 14 27](https://user-images.githubusercontent.com/96185920/178298605-13ce69b4-f8a9-44aa-a9d5-81d3b3893e8e.png)

The error is happening for every version between 15.0.1 and 16.1.1 included.
I tried to delete the node_modules folder and do `yarn install` again, but it doesn't change anything.
I'm using yarn v 1.22.19.
I also tried to upgrade the Keycloakify version in the package.json to its latest release (5.7.0) but nothing changed.

If I run the command for an higher Keycloak version (between 17 and latest) or for Keycloak v 11.0.3, I don't have the error and the folder is created but there is a problem in the email template, it is written [object Object] instead of the required action name. (cf screenshot, here with a "verify_email", but it does the same for all other required actions).  
This part is the real issue.

![Capture d’écran 2022-07-11 à 16 48 46](https://user-images.githubusercontent.com/96185920/178292166-ece1e56d-cc70-4f09-bcff-880f03083aea.png)

Maybe the arguments changed between version ? I couldn't find the information over the net nor a way to fix that.
If I remove the theme from the admin console, the text is the good one, it only happens when I apply the custom theme.

Do you think that the "[object Object] error" really come from a wrong Keycloak version chosen when running `npx create-keycloak-email-directory` or from something else ? Did anyone already encounter/solve this issue ?

I hope this is not too confuse, I can give you more details if needed,
Thank you for your time and your help,

Ps: Sorry for the long title, I didn't manage to make one better than that to resume the issue.

**Comment by clementinedeb** [comment]
Hello, 
thanks for the quick answer, I will pull the latest release as soon as it is available.

So the [object Object] text really is due to the wrong Keycloak email template's version ?

**Comment by garronej** [comment]
Hi @clementinedeb,  
The new release has been published 14h ago.  
I don't know about the error [Object Object] but you won't get any error with `npx create-keycloak-email-directory`.  
Tell me if the problem persist after using the emails for your keycloak version

**Comment by clementinedeb** [comment]
Hello, 
Thanks to your release I could use the email template for keycloak 16.1.1 but unfortunately I got the same [object Object] error when I use the theme... Do you want me to create another issue for this ?

**Comment by clementinedeb** [comment]
Ok, no problem, I'm opening a new issue with all needed informations :)
