### ISSUE TITLE
Using custom theme with Keycloak 16.1.1 cause Keycloak email's redirect link to show a page with [object Object] instead of required actions' names (like "verify email")

### ISSUE THREAD

**Issue by clementinedeb** [InseeFrLab/keycloakify#135]
Hello,

I'm encountering a problem when using a custom theme and sending emails with Keycloak.

To reproduce:
- Go to the Keycloak admin console and apply a custom theme
- Select a user (one whose inbox you can access) and go to the "credentials" tab
- Choose a reset action (like "verify email") and send an email
- Go to the inbox of the selected user, open the mail and click on the link inside it
- Here, you are redirected on a keycloak web page with the custom theme and you can see [object Object] instead of the required actions name.
- If you put back the default keycloak theme, the actions' names appear back in the page.

Here is a screenshot of the web page without theme, and below the one with the theme.

![Capture d’écran 2022-07-12 à 12 05 21](https://user-images.githubusercontent.com/96185920/178466059-1b481e87-f5f9-47a9-ba3c-c2e06ff4431a.png)

![Capture d’écran 2022-07-12 à 12 06 34](https://user-images.githubusercontent.com/96185920/178466276-04cd233c-b339-4f80-8cb8-54677bdfbce8.png)

I'm using:
- A project  forked from the demo app (to only customize some css)
- Keycloak 16.1.1
- Keycloakify in latest version (5.7.0)

No matter which version of keycloak email template I choose when typing `npx create-keycloak-email-directory` (from 11 to 18), I got the same result.

I searched for any informations on the internet but didn't manage to find what was causing this issue.
If anyone has an idea of why this happens or how to resolve it, it would be awesome.

Thanks for your time and your help.

**Comment by garronej** [comment]
Thanks for the detailed issue,  
Could you give me the id of the page that shows `[Object object]` by typing `kcContext.pageId` in the console.  
Example:     

<img width="2055" alt="image" src="https://user-images.githubusercontent.com/6702424/178510467-cf810962-5a31-4c24-b9e6-f28e33fba027.png">

**Comment by garronej** [comment]
can you do `JSON.stringify(kcContext)` and past the result here 🙏🏻

**Comment by garronej** [comment]
@clementinedeb I fixed the issue.  
There is a new release published: 5.7.2  

Thank you very much for reporting!
