### ISSUE TITLE
login.ftl generates keycloak errors

### ISSUE THREAD

**Issue by BartlomiejZalas** [InseeFrLab/keycloakify#140]
On every request to login.ftl generated by keycloakify the following error is displayed in the keycloak logs:

```
[freemarker.runtime] Error executing FreeMarker template part in the #attempt block: freemarker.core.InvalidReferenceException: The following has evaluated to null or missing:
object[key] [in template "login.ftl"] at line 70, column 37
```

The page works fine but it generates a lot of misleading messages in our logs. 
Any chances to fix that issue?

**Comment by garronej** [comment]
Can't reproduce.  
You probably aren't running the last version of Keycloakify.  
If you are, what version of Keycloak are you using?

**Comment by BartlomiejZalas** [comment]
We've been using version `4.2.10`. Upgrade to `4.2.14` fixed the issue. Thanks.

**Comment by garronej** [comment]
Thanks for the feedback

**Comment by BartlomiejZalas** [comment]
@garronej is there a migration guide available anywhere?

**Comment by garronej** [comment]
This is the commit where I did the migration from v4 to v5 in the demo app:  https://github.com/garronej/keycloakify-demo-app/blob/a5b6a50f24bc25e082931f5ad9ebf47492acd12a/src/index.tsx#L46-L63
