### ISSUE TITLE
Chunks are loaded from `/static`

### ISSUE THREAD

**Issue by ferretwithaberet** [InseeFrLab/keycloakify#141]
I am using `React.lazy` to benefit from code-splitting, but the app tries to load the chunks from `/static`(Example `http://localhost:8080/static/js/498.e475ad48.chunk.js` the correct one being `http://localhost:8080/resources/diqsw/login/keycloak-themes-react/build/static/js/498.e475ad48.chunk.js`).

I created the app using `yarn create react-app` then added `keycloakify` and `@emotion/react`. The app works fine if I start it with `yarn start`.

**Comment by garronej** [comment]
Hi @ferretwithaberet,  

Please produce a minimal repo that reproduce the issue ans I'll look into it.

**Comment by garronej** [comment]
And please make sure you are using the latest version of Keycloakify

**Comment by ferretwithaberet** [comment]
> Please produce a minimal repo that reproduce the issue ans I'll look into it.

[There you go.](https://github.com/ferretwithaberet/keycloakify-code-splitting-issue)

**Comment by garronej** [comment]
I wrote the test, now I need to implement.

**Comment by garronej** [comment]
I have done an implementation but it's so uneficient that any app would take ages to build.  
Need to refactor.

**Comment by garronej** [comment]
It's done 🥳  
Thanks for reporting I'll be able to use to levrage `React.lazy()` for improving perfomances for thoses not using `--external-assets`!

**Comment by AlexandrValerevich** [comment]
Faced with same issue but in little bit another form.

If I build the same code several times one .jar file work well and use `/resources/{id}/static/...` path for fetching recourses (expected behavior) and sometime it change path to `static/...` and get failed.
