### ISSUE TITLE
A way to use external assets on relative paths

### ISSUE THREAD

**Issue by satanshiro** [InseeFrLab/keycloakify#145]
I might have missed something but I can't set homepage on package.json file to "/" or of the sort so the external assets direct to a js file on base homepath of the webserver.
my deployment is keycloak behind an api gateway. i.e. "/auth" and the react app is on "/"
I would like an option to set homepage to lets say current hostname so I can deploy to various environments without changing the variable

**Comment by garronej** [comment]
Hi @satanshiro,  

Hum, I see.  
Indeed it's not supported, I didn't think about this usecase.  

I am currently working on a support of `React.lazy` for Keycloakify, I think it would make `--external-assets` irrelevant.  
What do you think?

**Comment by satanshiro** [comment]
It depends on how you implemented it, at the end of the day if we want all js served from outside of keycloak whether lazy or not it won't make --external-assets irrelevant. my guess is for big apps having a different deployment handle the assets would be important regardless if lazy or not. in any case it should be easy to add I saw the code here https://github.com/InseeFrLab/keycloakify/blob/317ad8386c81f29c89816a705eb7b28abf531d33/src/bin/build-keycloak-theme/build-keycloak-theme.ts#L47
I just can't insert to the url object anything that's not a baseurl.

**Comment by garronej** [comment]
Ok, I'll keep `--external-assets` and I'll see what I can do about your problem

**Comment by satanshiro** [comment]
another reason to keep --external-assets would be browser optimizations, when navigating to a different html but with same script file imports. (I can't find documentation but this was common ground 10 years ago before spa so browsers definitely have optimizations for that).
in any case what I would also put my eye on if you have the time is bundle size, my app is very basic at the moment but keycloakify alone doubled the size a difference of the production build by one megabyte.

**Comment by garronej** [comment]
> another reason to keep --external-assets would be browser optimizations, when navigating to a different html but with same script file imports.  

Yes, this is the reason why I created `--external-assets`.  

> in any case what I would also put my eye on if you have the time is bundle size, my app is very basic at the moment but keycloakify alone doubled the size a difference of the production build by one megabyte.  

I mean there is indeed a problem with Keycloakify bundle size, curently, it bundles every translation for every page and every language.  
The language and the pages should be downloaded laizily. I am working toward this, I added support for `React.lazy()` last night.  
[One megabyte seems a bit much though](https://bundlephobia.com/package/keycloakify@5.8.1):  
<img width="1501" alt="image" src="https://user-images.githubusercontent.com/6702424/181491969-7d116b16-fea4-4197-8f2c-9c7a6ad3df0b.png">

**Comment by garronej** [comment]
Just a quick update to say that I didn't forget you, v6 will solve all your issues

**Comment by garronej** [comment]
Hi @satanshiro,  
Things are ready. If you want to test with `"keycloakify": "6.0.0-beta.13"`.  
I have added a build option documented here: https://docs.keycloakify.dev/v/v6/build-options#keycloakify.isappandkeycloakserversharingsamedomain  

You'll just have to add this to your package.json:   

```json
{
    "keycloakify": {
        "isAppAndKeycloakServerSharingSameDomain": true
    }
}
```

and build with `--external-assets`   

> in any case what I would also put my eye on if you have the time is bundle size, my app is very basic at the moment but keycloakify alone doubled the size a difference of the production build by one megabyte.  

I have also took this input very seriously and I am happy to say that in V6 everything is lazy loaded, Keycloakify has now very little impact on the bundle size and first print is significantly faster.   

Please have a look at the migration guide: https://docs.keycloakify.dev/v/v6/   

In the hope of getting your feedback.  

Best

**Comment by satanshiro** [comment]
hey! will test pronto, and update.
this feature comes right in time!
thank you for your dedicated work!

**Comment by garronej** [comment]
Cool, hope it works, it should but I didn't took the time to setup an ingress controller and everything to guarentees it.  
Comme back to me if you are experiencing any issues

**Comment by satanshiro** [comment]
hey!
I'm closing the issue
works great and tested on my end.
thanks!

**Comment by garronej** [comment]
![image](https://user-images.githubusercontent.com/6702424/189691980-93362038-8cbb-447a-a3e1-f0268f2d094a.png)
