### ISSUE TITLE
Official website can not open？

### ISSUE THREAD

**Issue by meimosor** [InseeFrLab/keycloakify#149]
Official website can not open？

**Comment by garronej** [comment]
Thx for reporting

**Comment by garronej** [comment]
In the meantime https://docs.keycloakify.dev

**Comment by garronej** [comment]
@meimosor In the meantime you can access the doc here: https://github.com/InseeFrLab/keycloakify/tree/v5_docs

**Comment by meimosor** [comment]
> @meimosor In the meantime you can access the doc here: https://github.com/InseeFrLab/keycloakify/tree/v5_docs

OK, thank you very much
