### ISSUE TITLE
Quotes in `HTML Display name` can lead to undefined errors

### ISSUE THREAD

**Issue by hugocortes** [InseeFrLab/keycloakify#15]
I ran into an undefined error which was preventing my login page from rendering due to having this on my realm:
```
HTML Display name: <div class="kc-logo-text"><span>Keycloak</span></div>
```

Removing that value fixes the issue so there is a workaround. Based on the output, the `"` appear to be causing the issue. I'm not sure why I used that setting in the past (may be default?) but I imagine this library would render it obsolete.

The full rendered snippet is here: https://pastebin.com/kdNU2vY8

**Comment by garronej** [comment]
Brilliant, thank you for taking the time to report even though you found a workaround. 
I understand what's going on and will release a fix soon.

**Comment by garronej** [comment]
Fixed thx
