### ISSUE TITLE
Split css does not have keycloak resource path preprended

### ISSUE THREAD

**Issue by hugocortes** [InseeFrLab/keycloakify#16]
I'm pretty new to react and this is more of a question than an issue and it may not even be an issue with this library.

Some background on what I'm trying to achieve:
I would like to use a single Keycloakify project to render different themes for multiple clients based on the clientId kc context value. In the past, I would simply extend a theme and append to the `styles` property with the file path to client specific css to override the previous styles. Is there a way to do that with this library?

I first tried to import the css path as I do with favicon `import client1Favicon from "app/assets/client1/favicon.ico";` and append that to `styles` but I had no luck with that as the value was an object. But I'll continue looking into this, there may be some webpack option I can use to address this.

I also tried using code splitting feature to generate multiple css files but I now receive 404s as the Keycloak resource path is not prepended, example:
```
https://REDACTED/auth/resources/31exq/login/keycloakify/build/static/css/main.761845f0.chunk.css
https://REDACTED/static/css/4.75c36a70.chunk.css
```
Only the `main.*` chunks are available. Would it be possible for this to be fixed in the build-keycloak-theme scripts?

Here's a snippet of my components:

Main component:
```jsx
const Component = lazy(() => {
  return Promise.resolve(import("./path/to/component2"));
});

export const Login = ({ kcContext, ...kcProps }: KcContextLoginComponent) => {
  return (
    <Suspense fallback={<DefaultLogin {...props} />}>
      <Component {...props} />
    </Suspense>
  )
};
```

Component2
```jsx
import "./component2.scss";

const Component2 = memo((props: KcContextLoginComponent) => {
  return <Login {...props} />;
});
Component2.displayName = "Component2";

export default Component2;
```

Here's my resulting build folder directory `build_keycloak/src/main/resources/theme/keycloakify/login/resources/build/static`:
```.
.
├── css
│   ├── 3.976b061b.chunk.css
│   ├── 3.976b061b.chunk.css.map
│   ├── 4.1a7cc1a2.chunk.css
│   ├── 4.1a7cc1a2.chunk.css.map
│   ├── main.1bbd513a.chunk.css
│   └── main.1bbd513a.chunk.css.map
├── js
│   ├── 2.62a3ec59.chunk.js
│   ├── 2.62a3ec59.chunk.js.LICENSE.txt
│   ├── 2.62a3ec59.chunk.js.map
│   ├── 3.f64e32e6.chunk.js
│   ├── 3.f64e32e6.chunk.js.map
│   ├── 4.30b8d41c.chunk.js
│   ├── 4.30b8d41c.chunk.js.map
│   ├── 5.66f9d5bf.chunk.js
│   ├── 5.66f9d5bf.chunk.js.map
│   ├── main.66a4253a.chunk.js
│   ├── main.66a4253a.chunk.js.map
│   ├── runtime-main.0d72eac6.js
│   └── runtime-main.0d72eac6.js.map
└── media
    ├── banner.8160ab86.png
    ├── favicon.0c02463a.ico
    ├── favicon.5d99451e.ico
    ├── favicon.81150f84.ico
    ├── favicon.9115d06a.ico
    ├── favicon.9921761b.ico
    ├── favicon.ec5b0a49.ico
    ├── favicon.f5926395.ico
    ├── favicon.f6bfd61d.ico
    └── logo-text-300x63.e429c0bd.png
```

**Comment by garronej** [comment]
Hi @hugocortes thanks for reaching out,  
The fact that the resource is not prepended should be fixable by me.  
But I'll need an access to the source of your repo where you have Keycloakify setup to see exactly what is going on.

**Comment by hugocortes** [comment]
Awesome! Here's the repo to KcApp usage https://github.com/hugocortes/keycloak-themes/tree/master/src/app/components/KcApp. 

When debugging on local with `yarn start`, styling does work as expected

**Comment by garronej** [comment]
I think I understand the problem. Fixing...

**Comment by garronej** [comment]
It was hard, but I am happy to annonce that it is fixed.  
Thanks for reporting
