### ISSUE TITLE
KcContextBase.LoginConfigTotp

### ISSUE THREAD

**Issue by cfranco92** [InseeFrLab/keycloakify#161]
https://github.com/InseeFrLab/keycloakify/blob/832434095eac722207c55062fd2b825d1f691722/src/lib/components/LoginConfigTotp.tsx#L4

**Comment by garronej** [comment]
Hi @cfranco92,  
Please provide some context.

Regards

**Comment by garronej** [comment]
Feel free to reopen with aditional informations
