### ISSUE TITLE
Default styles and testing

### ISSUE THREAD

**Issue by inomn** [InseeFrLab/keycloakify#177]
Hi! First of all, thank you for this package. I have a few issues, maybe you can help me ([keycloakify-starter](https://github.com/garronej/keycloakify-starter)):

- How can I exclude default styles? Currently, default login.css is injected into the app (doFetchDefaultThemeResources is false)
- test layout for login page in development mode looks good (npm run start), however, after building template, uploading it into my keycloak, and selecting Login theme for my Realm - nothing happens, theme still looks default. In `build` directory there are `resources` folder, and `resources/build` contains my styles, but there are also `resources/css` with default styles, and bg images
Thanks. (copied from https://github.com/garronej/keycloakify-starter/issues/2)

Here are changes I made: https://github.com/inomn/keycloakify-test/pull/1/files

**Comment by garronej** [comment]
Hi @inomn,  


> doFetchDefaultThemeResources is false

**Comment by garronej** [comment]
@inomn,  

Thank you for mentioning that it wasn't possible to disable the fetching of the default asset on a peer page basis without in depth configuration.  

In v6.4.0 you can now optionally pass a `doFetchDefaultThemeResources: boolean` prop to every page component and the default `<KcApp />`
    This enables you to prevent the default CSS and JS that comes with the builtin Keycloak theme to be downloaded.  
    You'll get [a black slate](https://user-images.githubusercontent.com/6702424/192619083-4baa5df4-4a21-4ec7-8e28-d200d1208299.png).   

>  test layout for login page in development mode looks good (npm run start), however, after building template, uploading >it into my keycloak, and selecting Login theme for my Realm - nothing happens, theme still looks default. In build directory >there are resources folder, and resources/build contains my styles, but there are also resources/css with default styles, >and bg images
>Thanks. (copied from https://github.com/garronej/keycloakify-starter/issues/2)  


Regarding your second problem, make sure you have carfully read the instruction printed on your terminal after running `yarn keycloak` if you still have problem after that. Record your screen an show me what you are doing so I can try and help you.   

Best regards.

**Comment by inomn** [comment]
@garronej thanks a lot, it works!
