### ISSUE TITLE
How to serve the keycloak_static files

### ISSUE THREAD

**Issue by avishka40** [InseeFrLab/keycloakify#178]
I recently started playing with the keycloakify-starter(https://github.com/garronej/keycloakify-starter/tree/main)  project where once I have built the keycloak theme ,I successfully plugged in to my dockerized keycloak instance. However when loading the the user login screen it is requesting for some resources which are available under build/keycloak_static.

Is the intended behaviour from the theme to load certain resources from keycloak_static folder ? or Am I missing something here?

**Comment by avishka40** [comment]
Alright thanks for the quick reply , I am seeing certain resources being loaded  from the jar itself but some are being attempted  like https://keycloakdomain/keycloak_static/resources/css/login.css.
I will see if it is due to something due to a code change on my end and update here

**Comment by garronej** [comment]
It can be Keycloakify failing to fix the `urls`.  
It hapens often that a comunity member points out a new way of importing assets that I wasn't aware of.  

If it's the case and you can give me a reproduction path in the form of a demo repo I'll release a fix. I thake this kinds of reports seriously.  

Best reards,

**Comment by avishka40** [comment]
Ye I figured the issue was on my end , sorted it out. Thanks a lot for the quick help.
This work is really amazing, thanks for working on this.

**Comment by PhungVanHoa** [comment]
> Ye I figured the issue was on my end , sorted it out. Thanks a lot for the quick help.
> This work is really amazing, thanks for working on this.

how did you solve the problem?

**Comment by avishka40** [comment]
> 

I had to make sure to comment KcContext.ts   "mockPageId": "login.ftl" in line no 5 when building the starter.

**Comment by PhungVanHoa** [comment]
> I had to make sure to comment KcContext.ts "mockPageId": "login.ftl" in line no 5 when building the starter.

thank you
