### ISSUE TITLE
Module parse failed: Unexpected token

### ISSUE THREAD

**Issue by stephane-segning** [InseeFrLab/keycloakify#19]
Hi. Thank you for this nice library. I'm a Keycloak and react developer since a while and I was very excited to discover this library. So I'm about to convert my themes using this library. Now I have this error stopping me from going further.

I obtain this error when I try to run the dev server after adding my own config, based on [this](https://github.com/garronej/keycloakify-demo-app/tree/look_and_feel) config.

```bash
./node_modules/keycloakify/src/lib/components/Template.tsx 3:12
Module parse failed: Unexpected token (3:12)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| 
| import { useReducer, useEffect, memo } from "react";
> import type { ReactNode } from "react";
| import { useKcMessage } from "../i18n/useKcMessage";
| import { useKcLanguageTag } from "../i18n/useKcLanguageTag";
```

I've added these libraries because I need material inside my design:
```json
...
"@fontsource/roboto": "^4.4.5",
"@material-ui/core": "^4.12.0",
...
```

This is my `kcContext` : 
```typescript
import {getKcContext} from "keycloakify";

declare type RegisterType = {
    pageId: "register.ftl";
    phoneNumber: string;
}

declare type PhoneTanType = {
    pageId: "request-sms-tan.ftl";
    phoneNumber: string;
}

export const {kcContext} = getKcContext<RegisterType | PhoneTanType>({
    "mockPageId": "request-sms-tan.ftl",
    "mockData": [
        {
            "pageId": "request-sms-tan.ftl",
            "phoneNumber": "+234567890987"
        },
    ]
});

export type KcContext = NonNullable<typeof kcContext>;
```

Now when I use a pure js project, I don't have this error. After some researches, Webpack is the problem, not knowing how to load "import type" (obviously 😆).

Does someone have an Idea how to deal with such a situation?

**Comment by garronej** [comment]
Glad you find this library useful,
This should be an easy fix. Type only Imports and Export where introduced later on in TypeScript, at v3.8, released February 20th, 2020. 
Update [ts-loader](https://github.com/TypeStrong/ts-loader) in your project and you should be good. 😃

**Comment by stephane-segning** [comment]
Hi! Thanks for the prompt response. So I wasn't using `ts-loader`, so I installed it, and retried, without success. I've tried the version 9 (requesting webpack v5) and 8 (requesting webpack v4, what is used within this plugin)

**Comment by stephane-segning** [comment]
Some updates. Following [this](https://blog.johnnyreilly.com/2021/01/02/create-react-app-with-ts-loader-and-craco/) tutorial, I've come across a way to add ts-loader into the webpack so I've tried. Without success, the same error didn't even changed. So I'm thinking of redoing the whole project using babel and not create-react-app with typescript.

How come I don't get any error when using the default `KcApp`?

**Comment by garronej** [comment]
Sorry I don't have time to investigate, right now but if you link me your repo I can have a look later on.  
keycloakify is made for `create-react-app` if you start fresh it should work.  
Did you have a look at [this video](https://www.youtube.com/watch?v=xTz0Rj7i2v8)? note (the project have been renamed form keycloak-react-theming to keycloakify since this video was recorded)

**Comment by stephane-segning** [comment]
Ok, found this. I had a wrong import inside the code. Somewhere was imported `keycloakify/src/lib` instead of `keycloakify/lib` and it did all the difference. Now it's working like a charm.
Thank you for support 😉

**Comment by garronej** [comment]
I am sorry, I should have figured out this myself. Glad you sorted this out!
