### ISSUE TITLE
Injecting Template or Template props on KcApp

### ISSUE THREAD

**Issue by julio-louzada** [InseeFrLab/keycloakify#191]
First of all thanks for the great work!

I'm trying to use Keycloakify with the least cost of development, but there is a huge gap between only changing the `css` and adding any kind of customization involving `js` or `html`. My current use case is to simply add a logo on the Header Title (for ex. `Sign In` on the Login page).

I'm unable to do it in a simple manner because the base component `Template.tsx` is hardcoded on the page components, which makes it impossible to change the Header for every page (I'd need to copy-paste everything for a simple props change in `Template`).

Would it be possible to have injected the `Template` component inside `KcApp` or at least **make the props from the Template component available to KcApp**? (some care must be taken since we need to access runtime props like **i18n** when passing them down, so we can continue to use the good support already existing in Keycloakify.

Many thanks!

**Comment by garronej** [comment]
Hi @julio-louzada, thanks for reaching out.

> Would it be possible to have injected the Template component inside KcApp  

Yes, this would make a lot of sense, I'll do that.

**Comment by garronej** [comment]
I didn't forget.  
I just didn't find the time yet...

**Comment by garronej** [comment]
Hi @julio-louzada,  

That's it, it's possible in Keycloakify v6.8.0.  

https://github.com/InseeFrLab/keycloakify/blob/85a68357482268696be32b0d7f8d67ab6309bbd3/README.md?plain=1#L52-L56  

Thank you for suggesting this enhancement,
