### ISSUE TITLE
What is the equivalent to `advancedMsg` ?

### ISSUE THREAD

**Issue by stephane-segning** [InseeFrLab/keycloakify#20]
Hello, during the conversion of my themes from Keycloak Freemarker to keycloakify, I came across this problem. Actually, there's no equivalent to `advancedMsg` when using this library, or I didn't found any.

```ftl
<#if client.name?has_content>
      ${msg("oauthGrantTitle",advancedMsg(client.name))}
<#else>
      ${msg("oauthGrantTitle",client.clientId)}
</#if>
```

This is what I've tried:
```typescript
client.name ? msgStr('oauthGrantTitle', msgStr(client.name)) : msg("oauthGrantTitle", client.clientId
```

but without surprise, I'm getting an error:
- First typescript error - because they're not from the same type
- Second dom error - this means, that no text is being printed to the screen during development.

Do you have an idea how I can do it right ?

**Comment by garronej** [comment]
Hi,  
Looking at [this](https://github.com/keycloak/keycloak/blob/master/services/src/main/java/org/keycloak/theme/beans/AdvancedMessageFormit seems it evaluate a string composed of multiple translation token...   
Could you give me the expected input output of `advanceMsg`?  

> ```ts
> msgStr('oauthGrantTitle', msgStr(client.name))
> ```

When I look at what `"oauthGrantTitle"` correspond to in english it's  `"Grant Access to {0}"`...

It seems to me that this would do: 

```ts
msgStr("oauthGrantTitle", client.name ?? client.clientId )
```

I have added `name` and `clientId` to the types definitions for you in v2.0.7

Regards

**Comment by stephane-segning** [comment]
Hello, 

The thing is working, but in comparison to this one:

```ftl
<li>
     <span>${advancedMsg(clientScope.consentScreenText)}</span>
</li>
```

using 
```tsx
msgStr(scope.consentScreenText as any)
```

is not working. That's why I'm asking here

**Comment by garronej** [comment]
If you give me the expected input/output I can implement a `advancedMsg` function.

**Comment by stephane-segning** [comment]
This is the current result of the implementation:
<img width="484" alt="Screenshot 2021-07-12 at 20 30 30" src="https://user-images.githubusercontent.com/26783557/125338028-63726280-e358-11eb-82a4-6b23396274a9.png">
- So for the title, it's working great
- But for each scope, there's no text for each proposition

[This](https://www.keycloak.org/docs-api/14.0/javadocs/org/keycloak/forms/login/freemarker/model/OAuthGrantBean.html) is the model for the `oauth` and [here](https://www.keycloak.org/docs-api/14.0/javadocs/org/keycloak/models/ClientScopeModel.html) is the content of the client scope model `clientScope` (I'm currently using the keycloak v14).

Now for each `clientScope` there is a `consentScreenText` and I suppose it `advancedMsg` just look for the correct i18n name for each value. It it doesn't find anything, the key is returned as provided default value

**Comment by garronej** [comment]
> Now for each `clientScope` there is a `consentScreenText` and I suppose it `advancedMsg` just look for the correct i18n name for each value. It it doesn't find anything, the key is returned as provided default value

Could you run your old theme and give, me for this instruction for example, `${advancedMsg(clientScope.consentScreenText)}` what is the value of `clientScope.consentScreenText` and what is the expected output?

**Comment by stephane-segning** [comment]
So after some researches, I came across this page in production:
<img width="469" alt="Screenshot 2021-07-15 at 16 20 49" src="https://user-images.githubusercontent.com/26783557/125804018-061ed868-7dd2-40ca-a2eb-b56257b0f449.png">

I came accross one of these texts [here](https://github.com/keycloak/keycloak/blob/master/themes/src/main/resources/theme/base/account/messages/messages_en.properties#L64) and [here](https://github.com/keycloak/keycloak/blob/master/themes/src/main/resources/theme/base/login/messages/messages_en.properties#L91).

It's as if they were translation messages, but they still have the `$` and `{` `}` structure.

**Comment by garronej** [comment]
Sorry, I didn't have the time to investigate yet but I will do it sooner or later.

**Comment by garronej** [comment]
It's done... eventually. [See code](https://github.com/InseeFrLab/keycloakify/blob/392377bf2d03b18a171d726d696f3794f5de04ee/src/lib/i18n/useKcMessage.tsx#L55-L70)

**Comment by ckqbao** [comment]
Hi @garronej,
I would like to know where we can access to oauth variable ?
