### ISSUE TITLE
Unzip not found when building the keycloak theme

### ISSUE THREAD

**Issue by bakh4966** [InseeFrLab/keycloakify#206]
Hi @bakh4966,  

I'll need more info, your screen shot is cropped I can't see the relevent part.  
And please open another ticket.

_Originally posted by @garronej in https://github.com/InseeFrLab/keycloakify/issues/54#issuecomment-1314333154_
      

Hi @garronej again, here I attached more detailed image, this problem is happening when I try to build the project, not only advanced its happening in starter project as well

![Снимок экрана 2022-11-15 102744](https://user-images.githubusercontent.com/22908130/201826371-230604b6-9b85-4745-8c7f-830a1cd31390.png)

**Comment by garronej** [comment]
`sudo apt-get install zip unzip`

**Comment by bakh4966** [comment]
Ooh maaan thx a lot!!!

**Comment by garronej** [comment]
You are welcome !
