### ISSUE TITLE
How to access new custom page  

### ISSUE THREAD

**Issue by oha95** [InseeFrLab/keycloakify#208]
Hello, 

I can't find how to create a link to a new custom page, how can I add the link in kcContext.url?

**Comment by garronej** [comment]
Hi @oha95,  

I assume you have followed the instruction [here](https://docs.keycloakify.dev/limitations#i-have-established-that-a-page-that-i-need-isnt-supported-out-of-the-box-by-keycloakify-now-what) under the tab `I do it only for my project`?  

> how can I add the link in kcContext.url ?  

You can't. It's Keycloak that generates te kcContext, keycloakify only translates it into Javascript.  

If you realy have implemented a page that is custom. Meaning that isn't known by Keycloak you don't need Keycloak for the rooting.  
You can handle it on your own. It's an SPA after all.
