### ISSUE TITLE
Tailwind CSS

### ISSUE THREAD

**Issue by Quadrisheriff** [InseeFrLab/keycloakify#211]
I'll like to ask if it's possible to use Tailwind CSS with Keycloakify. If yes, can you guys help with a guide or anything that can help?

**Comment by garronej** [comment]
Yes, of course...  
The general answer for all the question about compatibility is: If it works in a Create React App project, it works for keycloakify. 
There's nothing specific to know about it.  
Clone the starter repo, css only or indeph depending on how mutch you want to customize and follow this guide: https://tailwindcss.com/docs/guides/create-react-app  

Let me know if you have issues getting started
