### ISSUE TITLE
Dynamically change login page appearance based on redirect_uri

### ISSUE THREAD

**Issue by hookenful** [InseeFrLab/keycloakify#212]
Hi there!

I've seen [solution](https://github.com/dteleguin/keycloak-dynamic-branding) and its [mail discussion](https://lists.jboss.org/pipermail/keycloak-user/2018-October/015876.html), which helps to push url info into FTL templates. Currently, we are using your solution to customise login theme. 
Is it possible to merge this one with yours to achieve dynamic branding? 

Thanks for any info!

**Comment by garronej** [comment]
Hi @hookenful,  

There is no need to use the mentioned sollution, you have all the power. You are in a reac app. You can just read `window.location.href`!  

Here you have all explaination about how you can pass params in the url before redirecting and getting them back in the Keycloak theme.  
https://docs.keycloakify.dev/context-persistence

We use that ourself for theme customization:  
Theme 1: https://auth.lab.sspcloud.fr/auth/realms/sspcloud/protocol/openid-connect/auth?client_id=onyxia&redirect_uri=https%3A%2F%2Fdatalab.sspcloud.fr%2Fhome&state=ddbe3df8-3b12-4e2e-8979-5386f878ee8b&response_mode=query&response_type=code&scope=openid&nonce=ada9e6b6-c0e1-408a-83cb-92f40f40dee8&ui_locales=fr&THEME_ID=france&HEADER_ORGANIZATION=foobarbaz  
Theme 2: https://auth.lab.sspcloud.fr/auth/realms/sspcloud/protocol/openid-connect/auth?client_id=onyxia&redirect_uri=https%3A%2F%2Fdatalab.sspcloud.fr%2Fhome&state=ddbe3df8-3b12-4e2e-8979-5386f878ee8b&response_mode=query&response_type=code&scope=openid&nonce=ada9e6b6-c0e1-408a-83cb-92f40f40dee8&ui_locales=fr&HEADER_ORGANIZATION=somethingelse

**Comment by hookenful** [comment]
@garronej wow. I am really impressed with your keycloak & react adoption ^_^.  So do I need to use `transformUrlBeforeRedirect` function? 

And then create a hook where I use `retrieveParamFromUrl` function and do things with styles? Did I understand right?

**Comment by hookenful** [comment]
Hi, @garronej. We want to handle custom theme by resolving 3rd level domain name and take it and pass into param. 

For example, user is going to https://foobarbaz.treerim.org/

After he is redirecting to https://auth.treerim.org/auth/realms/only-auth/protocol/openid-
connect/auth?client_id=only-auth&redirect_uri=https%3A%2F%2Ftreerim.org%2Fhome&state=ddbe3df8-3b12-4e2e-8979-5386f878ee8b&response_mode=query&response_type=code&scope=openid&nonce=ada9e6b6-c0e1-408a-83cb-92f40f40dee8&HEADER_ORGANIZATION=foobarbaz . 
And there all magic which you described works. Is it possible?

**Comment by garronej** [comment]
Yes, you'll do something like this

```typescript
import keycloak_js from "keycloak-js";
import { createKeycloakAdapter } from "keycloakify";
import { addParamToUrl } from "powerhooks/tools/urlSearchParams";

//...

const keycloakInstance = keycloak_js({
    "url": "http://keycloak-server/auth",
    "realm": "myrealm",
    "clientId": "myapp",
});

keycloakInstance.init({
    "onLoad": "check-sso",
    "silentCheckSsoRedirectUri": window.location.origin + "/silent-check-sso.html",
    "adapter": createKeycloakAdapter({
        "transformUrlBeforeRedirect": url=>
            [url]
                .map(url => addParamToUrl({ url, "name": "HEADER_ORGANIZATION", "value": "foobarbaz" }).newUrl)
                [0],
        keycloakInstance,
    }),
});
```  

But you'll be responsible of parsing the param on the other side.  

If you want it abstracted away for you, just use the `powerhooks/useGlobalState` approach.  
It's by far the easyest way:  https://docs.keycloakify.dev/context-persistence
