### ISSUE TITLE
Deploy custom theme to real instance

### ISSUE THREAD

**Issue by houssemmimoun27** [InseeFrLab/keycloakify#214]
Hi
How to deploy the keycloakify build jar file to a real keycloack instance

**Comment by garronej** [comment]
Hi @houssemmimoun27,  

You have to drop the `.jar` file in `/opt/keycloak/providers`   

See: https://github.com/InseeFrLab/keycloakify/blob/23f6c7db00ece3dfdfa8d0108e50d3da32847e9a/src/bin/keycloakify/keycloakify.ts#L67-L117
