### ISSUE TITLE
Possible security flow : username enumeration if anti brute force activated

### ISSUE THREAD

**Issue by remigauthierdocaposte** [InseeFrLab/keycloakify#217]
Hello all,

We noticed that if the brute force is activated and if an account is blocked, the response generated using Keycloakify different than with a classic user/password failure. Thus the attacker will be able to induce that a username exists when blocking the account. If this is automated, an attacker can guess all username and carry on other attacks using these sensitive informations (targetted phishing, password guess...).

The payload incriminated on browser side :

If the user is not blocked :

     out["messagesPerField"]= {
    
        "printIfExists": function (fieldName, x) {
                    if(fieldName === "global" ){
                            return "" ? x : undefined;
                    }
                    if(fieldName === "userLabel" ){
                            return "" ? x : undefined;
                    }
                    if(fieldName === "username" ){
                            return "" ? x : undefined;
                    }
                    if(fieldName === "email" ){
                            return "" ? x : undefined;
                    }
                    if(fieldName === "firstName" ){
                            return "" ? x : undefined;
                    }
                    if(fieldName === "lastName" ){
                            return "" ? x : undefined;
                    }
                    if(fieldName === "password" ){
                            return "1" ? x : undefined;

If the user is blocked :

    out["messagesPerField"]= {
    
        "printIfExists": function (fieldName, x) {
                    if(fieldName === "global" ){
                            return "" ? x : undefined;
                    }
                    if(fieldName === "userLabel" ){
                            return "" ? x : undefined;
                    }
                    if(fieldName === "username" ){
                            return "1" ? x : undefined;
                    }
                    if(fieldName === "email" ){
                            return "" ? x : undefined;
                    }
                    if(fieldName === "firstName" ){
                            return "" ? x : undefined;
                    }
                    if(fieldName === "lastName" ){
                            return "" ? x : undefined;
                    }
                    if(fieldName === "password" ){
                            return "" ? x : undefined;

I am going to see if we can bypass this behavior on our side and if this is a missuse of the lib.
Meanwhile, I was hoping that you could investigate on your side and give a feedback on this.

Thanks in advance,
Rémi

**Comment by garronej** [comment]
Interesting, thank you for investigating this.  
At first thought I'd say that Keycloak should assume that info exposed to FTL isn't sensible.  
Otherwise it means that that theme author can inadvertently introduce security vulnerability.  
If we agree on this premise, I'd say that it's an issue for Keycloak.  
That being said, I can address this in Keycloakify, I don't think it's my responsibility to do so but if Keycloak doesn't address this, I will.

**Comment by garronej** [comment]
@pedrodsRocha1 @remigauthierdocaposte,  
Thanks for the investigation and the fix.  
I think this is worth submiting an issue on the Keycloak repo.  
I assume this vulnerability itsn't present in the default theme but still, it could very well be in any other cutom theme don't you think?

**Comment by marcinkrasowski** [comment]
Hi, I've installed the latest version and apparently this causes errors in my app (with keycloak 18.0.2, and I'm using the "component level customization" to have custom implementation of the pages if that helps):
```
2023-01-10 07:11:00,734 ERROR [freemarker.runtime] (executor-thread-19) Error executing FreeMarker template part in the #attempt block: freemarker.core._TemplateModelException: Java method "org.keycloak.theme.beans.MessagesPerFieldBean.exists(String)" takes 1 argument, but 2 was given.

----
FTL stack trace ("~" means nesting-related):
	- Failed at: #if messagesPerField.exists("username...  [in template "login.ftl" at line 102, column 40]
----
```
Full log at https://gist.github.com/marcinkrasowski/52ab3606ee2fca442c2de1d288582c46

The generated FTL code in `login.ftl` looks like this:
```
        "exists": function (fieldName) {
            <#if !messagesPerField?? >
                return false;
            <#else>
                <#list fieldNames as fieldName>
                    if(fieldName === "${fieldName}" ){
                        <#attempt>
                            <#if '${fieldName}' == 'username' || '${fieldName}' == 'password'>
                                return <#if messagesPerField.exists('username', 'password')>true<#else>false</#if>
                            <#else>
                                return <#if messagesPerField.exists('${fieldName}')>true<#else>false</#if>;
                            </#if>
                        <#recover>
                        </#attempt>
                    }
                </#list>
                throw new Error("There is no " + fieldName + " field");
            </#if>
        }
```
Any ide what might be causing it? From what I've tested it doesn't cause any actual problems in application, but there is still an ugly error in logs that I would like to get rid off.

**Comment by garronej** [comment]
@marcinkrasowski,  
Sorry about that, I didn't test carefully enough this PR.

**Comment by marcinkrasowski** [comment]
The fix seems to be working well, thank you for super fast response :)

**Comment by garronej** [comment]
Great thanks!
