### ISSUE TITLE
Use of execSync to remove files and dirs makes this nonportable

### ISSUE THREAD

**Issue by lordvlad** [InseeFrLab/keycloakify#219]
Unfortunately, we cant run keycloakify from powershell or cmd, because of the use of system calls to execute `rm <args>`. (e.g. https://github.com/InseeFrLab/keycloakify/blob/2bfbba4daf786018de4ec7c519651f20658c0c17/src/bin/tools/rm.ts)
Consider using a nodejs function: https://stackoverflow.com/a/57866165/1568684

**Comment by garronej** [comment]
Yes sorry about that.  
In the mean time, many windows users have reported it working fine in WSL: https://github.com/InseeFrLab/keycloakify/issues/54#issuecomment-984834217

**Comment by garronej** [comment]
And by the way, I don't have the bandwith to do it, but if you submit a PR I'll quicky review it and publish a new release...
