### ISSUE TITLE
Using maven to bundle the jar add superfluous dependency

### ISSUE THREAD

**Issue by lordvlad** [InseeFrLab/keycloakify#220]
Effectively, maven creates a zip file. In addition to the theme files, there are 4 more files, two of which are created by keycloakify itself. We could easily replace the maven dependency by creating the zip archive using nodejs functions.

**Comment by lordvlad** [comment]
I'll take a swing at it

**Comment by garronej** [comment]
> I would also love it if the output artifact name and location was configurable. Reason being is that I'm using gradle, and in order to set up the build tasks correctly that allow for caching/skipping due to no changes, it helps to know the exact file paths of all inputs and outputs.  

Hi @mrpatrickpilch, wouldn't it be an option to `keyclaokify && mv ...`?

**Comment by mrpatrickpilch** [comment]
@garronej But what's the first argument to `mv`? That path is controlled by [your code](https://github.com/InseeFrLab/keycloakify/blob/v6.8.15/src/bin/keycloakify/generateJavaStackFiles.ts#L87), not mine. If I do `*.jar`, I still won't know what the file name is in my gradle build. I suppose I can write a function to parse it out of **package.json** and construct the file path myself, but now I have two path generation functions - yours and mine. Which is authoritative? I'd hate for them to get out of sync. If you relinquish control over those details to the consumer, I can control that in my gradle build and depend on it not changing out from underneath me. 

Elaborating on that thought - it would be helpful if you split out the build tasks. Right now it's all or nothing - the keycloakify task sets up the directory structure for the theme jar, and _also_ requires running maven. What if this was split into two phases? One task sets up a directory in the proper theme structure, and a separate task creates the jar. In my case, I simply won't run the latter task and handle it myself with Gradle. For backwards compatibility, the jar task can run maven as it always has. And hopefully in the future you can remove the dependency on maven entirely as @lordvlad suggests.

**Comment by garronej** [comment]
@mrpatrickpilch Thanks for the feedback.  
I see the problem. I don't have time to address it now but I agree.  
If you want to submit a PR I'll review it.

**Comment by lordvlad** [comment]
@mrpatrickpilch we have the same use case, so this is what I'm aiming at

**Comment by lordvlad** [comment]
@mrpatrickpilch actually a nice idea to split it into two steps, I woud've squashed  it into one and maybe added a cli param

**Comment by garronej** [comment]
> a nice idea to split it into two steps, I woud've squashed it into one and maybe added a cli param  

I would like `npx keycloakify` to be the only command.

**Comment by lordvlad** [comment]
@garronej sure, that would be required for backwards compatibility. Still you could split it and enable/disable later parts using config or cli or env vars

**Comment by lordvlad** [comment]
@mrpatrickpilch @garronej I didnt find a way to nicely 'split' it without too much refactoring, what I did instead was introduce an option to disable bundling (in addition to having an alternative nodejs-only bundler). Please find details on #239
