### ISSUE TITLE
Theme is not visible for selection

### ISSUE THREAD

**Issue by inomn** [InseeFrLab/keycloakify#224]
Hi! First of all thanks for this tool!
I'm using [CSS Starter](https://github.com/garronej/keycloakify-starter).

Here's how i'm trying to test my theme:
1. Build project
2. Copy jar archive to docker image using command
```
docker cp build_keycloak/target/custom-1.0.0.jar docker-image-hash:/opt/keycloak/providers/custom.jar
```
3. Restart docker

After doing that i don't see my custom theme anywhere, it's not available for selection.

If i extract jar archive and put it using the same command directly to themes folder, so 
```
docker cp build_keycloak/target/custom-1.0.0 docker-image-hash:/opt/keycloak/themes/custom
```

I still can't see my theme in
`Realm Settings -> Themes -> Login theme`
neither in
`Realms -> My realm -> Clients -> My client -> Settings -> Login settings -> Login theme`

Any ideas about what I'm doing wrong? Thanks.
p.s. in dev mode (npm start) theme looks good

**Comment by inomn** [comment]
hi @garronej , thanks for the answer. Yes, this is what i did and described at step 2:

```
docker cp build_keycloak/target/custom-1.0.0.jar docker-image-hash:/opt/keycloak/providers/custom.jar
```

so in `/opt/keycloak/providers` appears my custom.jar archive, and restarting the docker has no effect

**Comment by garronej** [comment]
@inomn Ok sorry I didn't read carefully enough.  

Have you tied with the theme of the starter to see if it's detected: https://github.com/garronej/keycloakify-advanced-starter/releases/download/v1.0.6/standalone-keycloak-theme.jar  

https://github.com/garronej/keycloakify-advanced-starter/releases/tag/v1.0.6

**Comment by inomn** [comment]
@garronej thank you, i find an issue. I thought keylock build providers automatically on launch, but actually, I missed the build command in my docker file. Now I see my custom theme, and the issue I have now is that the form action is `#` instead of actual URL, looks like 

```
<form id="kc-form-login" action="#" method="post">
```

trying to find the reason. with default theme action is right and login works

**Comment by garronej** [comment]
Thank you for reporting.  
I'll close this, you can open another issue about your other problem. 
Is the new problem you are experiencing also hapening with the theme from keycloakify-advanced-starter?   

Best
