### ISSUE TITLE
Customize saml-post-form.ftl

### ISSUE THREAD

**Issue by raafael** [InseeFrLab/keycloakify#229]
Hi! First of all I would like to congrats for this great project, so I have a storefront sso saml integration and after the login page the user is redirect to the page from keycloak called saml-post-form.ftl that I don't know how to customize, I tried the same approach as login but it seems that isn't declared KcContextBase.
![image](https://user-images.githubusercontent.com/5247148/212972050-39d9565d-9e33-4496-8d22-7f1fa2c434b2.png)

**Comment by garronej** [comment]
Hello @raafael,  
Thank you for the kind words.  
Yes, I'm sorry, some pages aren't supported yet.  
You could submit a PR to add support for this specific page though.  
It's not hard, everything is explained in the doc, and it would greatly benefit the community.  
If you don't have time for that, don't worry, there is also an option in the doc that explain how to make it work only for you.  

https://docs.keycloakify.dev/limitations#i-have-established-that-a-page-that-i-need-isnt-supported-out-of-the-box-by-keycloakify-now-what  

Let me know if you need more help.

**Comment by raafael** [comment]
@garronej  Thanks for your reply, so I was trying this part of the docs that you send me but I don't figure out how
to use the actions and conditions that exists for this template saml-post-form. The samples doesn't show if I want to use the variables that freemarker template use, like the code below for saml-post-form:

```freemarker
        <form name="saml-post-binding" method="post" action="${samlPost.url}">
            <#if samlPost.SAMLRequest??>
                <input type="hidden" name="SAMLRequest" value="${samlPost.SAMLRequest}"/>
            </#if>
            <#if samlPost.SAMLResponse??>
                <input type="hidden" name="SAMLResponse" value="${samlPost.SAMLResponse}"/>
            </#if>
            <#if samlPost.relayState??>
                <input type="hidden" name="RelayState" value="${samlPost.relayState}"/>
            </#if>

            <noscript>
                <p>${msg("saml.post-form.js-disabled")}</p>
                <input type="submit" value="${msg("doContinue")}"/>
            </noscript>
        </form>
```

Can I create a new saml-post-form and use this "samlPost" some how in my custom ftl?

**Comment by garronej** [comment]
Hello @raafael,  
You do not need to write any custom ftl.  
Have a look at `window.kcContext` you'll see, all the information you need to construct the page will be there (`kcContext.samlPost.url`...).  
You just need to define the types.  
Look at this PR from a contributor for example: https://github.com/InseeFrLab/keycloakify/pull/92  

The main work is to convert the `saml-post-form.ftl` file into React. But it's literal translation, there is no room for interpretation and creativity here.

**Comment by raafael** [comment]
Hi @garronej,
Thank you for your help. I manage to solve with a extra page, and add all the necessary types to the kcContext.
As soon I have some time I would like to contribute with this page in the project.

**Comment by garronej** [comment]
@raafael thank you for the feedback, congrats for making it work and yes please do, your contribution will be mutch valued!

**Comment by raafael** [comment]
Hello @garronej ,

Just one more question, I tried to use i18n to override some login messages but it seems that didn't work, may I missed something?

My i18n.ts

```ts
import { useI18n as useI18nBase } from "keycloakify";

type Props = Omit<Parameters<typeof useI18nBase>[0], "extraMessages">;

export function useI18n(props: Props) {
    const { kcContext } = props;
    return useI18nBase({
        kcContext,
        "extraMessages": {
            "pt-BR": {
                "invalidUserMessage": "Credênciais incorretas",                
                "invalidUsernameOrEmailMessage": "Credênciais incorretas",
                "invalidUsernameMessage": "Credênciais incorretas",
                "invalidPasswordMessage": "Credênciais incorretas"

            }
        },
    });
}

export type I18n = NonNullable<ReturnType<typeof useI18n>>;
```

**Comment by garronej** [comment]
Hi @raafael,  

What's not working exactly?  
What do you have in your `kcContext.local.currentLanguageTag` ?

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/6702424/213914973-d4a9b828-e21f-463a-965b-3a295090b337.png">

**Comment by raafael** [comment]
Hello @garronej ,

So the language it's correct:
![image](https://user-images.githubusercontent.com/5247148/214030522-b79e05fd-f6a1-4d6b-9ce6-d10657a3a0a2.png)

But the error message it's not the same that I set in i18n:
![image](https://user-images.githubusercontent.com/5247148/214031787-2964bc5f-6c9b-44f0-8594-b095f11dd1f6.png)

If I take a look in the .jar, I have the default message:
![image](https://user-images.githubusercontent.com/5247148/214033911-8a3679f5-5150-4eb8-9df4-279cdddd09d4.png)

But in my i18n ts I have:
"invalidUserMessage": "Credênciais incorretas",

**Comment by garronej** [comment]
Hi @raafael,  
Sory for the late reply,  
> If I take a look in the .jar, I have the default message:
The `.properties` files aren't relevent in Keycloakify.   

Did you fix the issue?  
If you share your code I'll be able to help.  
Are the examples given in the advanced starter repo working?

**Comment by luigidevelopment** [comment]
> ```ts
> "extraMessages": {
>             "pt-BR": {
>                 "invalidUserMessage": "Credênciais incorretas",                
>                 "invalidUsernameOrEmailMessage": "Credênciais incorretas",
>                 "invalidUsernameMessage": "Credênciais incorretas",
>                 "invalidPasswordMessage": "Credênciais incorretas"
> 
>             }
>         },
> ```

Can you do this?

**Comment by garronej** [comment]
I guess yes, it looks good to me.

**Comment by luigidevelopment** [comment]
Hi @garronej 

So, I'm trying to use kcContext to get extraThemeProperties on Login Page, but I can't because does not declared on kcContext.

Can you help me?

**Comment by garronej** [comment]
What do you mean by "not declared"?  On the type? Have tou tried opening your devlopement tool and `console.log(kcContext)`?  
See what's actually is in the kcContext.  

> And, on i18n, where is the correct file to use extraMessages?  

What do you mean by "use"?

**Comment by luigidevelopment** [comment]
> What do you mean by "not declared"? On the type? Have tou tried opening your devlopement tool and `console.log(kcContext)`? See what's actually is in the kcContext.
> 
> > And, on i18n, where is the correct file to use extraMessages?
> 
> What do you mean by "use"?

Yes, on the type. So, when I put on console, works, but I need to use in Login.tsx. Can I do this?

On i18n file, I managed to solve.

Thanks for your helping!

**Comment by garronej** [comment]
Well, if it's only that you want to have correct typing you can extand the base type definition of the `kcContext` object like so:  

<img width="1021" alt="image" src="https://github.com/keycloakify/keycloakify/assets/6702424/e6bf52c5-91e3-4ca6-afea-ad9858dfb9b3">

And after in the Login.tsx component you'll se your custom value listed:  

![image](https://github.com/keycloakify/keycloakify/assets/6702424/5c9404eb-090d-4d1c-97fd-a39123b872e8)  

Hope it helps.

**Comment by luigidevelopment** [comment]
Hi @garronej 

Thanks man! That's exactly what I was wondering about!
