### ISSUE TITLE
Error during the "build-keycloak-theme" execution

### ISSUE THREAD

**Issue by anyLetters** [InseeFrLab/keycloakify#23]
`keycloakify 2.0.10`
`Node 14.17.3`

I created a new project via `create-react-app`. `index.tsx` looks like this:

```
import ReactDOM from "react-dom";
import "./index.css";
import reportWebVitals from "./reportWebVitals";
import { KcApp, defaultKcProps, getKcContext } from "keycloakify";
import { css } from "tss-react";

const { kcContext } = getKcContext();

const myClassName = css({ color: "red" });

ReactDOM.render(
  <KcApp
    kcContext={kcContext!}
    {...{
      ...defaultKcProps,
      kcHeaderWrapperClass: myClassName,
    }}
  />
  ,
  document.getElementById("root")
);

reportWebVitals();
```

When I'm trying to run `yarn build && build-keycloak-theme` I'm getting this:

![image](https://user-images.githubusercontent.com/24977698/126190234-b725c969-f3fc-4b5f-9ef6-b5bd81de97db.png)

Downgraded versions of `Node` or `keycloakify` makes no difference.

I also tried the [demo-app](https://github.com/garronej/keycloakify-demo-app) and still got the same error.

Any ideas?

Thanks 😊

**Comment by garronej** [comment]
Hi,

Yeah, you are on Windows, only MacOS and linux are supported.  
Multiple people have reported it working with Windows Subsystem for Linux.

**Comment by anyLetters** [comment]
With wsl2 it works. Thanks!
