### ISSUE TITLE
`npx keycloakify` reports incorrect file path to JAR file

### ISSUE THREAD

**Issue by rome-user** [InseeFrLab/keycloakify#232]
After building the theme, the following message appears in the terminal.

> ✅ Your keycloak theme has been generated and bundled into ./build_keycloak/target/foobar-1.0.jar 🚀
> It is to be placed in "/opt/keycloak/providers" in the container running a quay.io/keycloak/keycloak Docker image.

However, the name of JAR file is `foobar-keycloak-theme-1.0.jar`. My `package.json` looks like this:
```json
{
  "name": "foobar",
  "version": "1.0",
  "private": true,
  ...
}
```

**Comment by garronej** [comment]
Thanks for reporting!
