### ISSUE TITLE
Possible to combine Registration & Login pages?

### ISSUE THREAD

**Issue by william-will-angi** [InseeFrLab/keycloakify#254]
Is it possible to have a single page that contains both login and registration capabilities? Currently when transitioning, there is a slight flash because it's loading a new page. I would like to have SPA-like transitions between the login and registration forms. Is this possible?

**Comment by garronej** [comment]
Hi @william-will-angi,  
Unfortunately no, it's a hard limitation on the Keycloak side :(  
That being said, it's posible to acheive a fully seamless transition with Lazy loading and resource caching.  
Have a look at our datalab login page: https://datalab.sspcloud.fr  

The transition looks prety seamless to me... 

https://user-images.githubusercontent.com/6702424/221960905-9f31bbc1-762a-4ca6-bc3e-8cbe6288c562.mov

Have a look at `--external-assets` if you want to dig deeper more: https://docs.keycloakify.dev/build-options#external-assets  

Hope it helps

**Comment by william-will-angi** [comment]
Thanks for the quick response @garronej! That makes sense, and I'll do some experimentation with that approach.

Follow-up: Is there a recommended approach for generating the initial HTML returned by keycloak? I would like to be able to include html tags to make it more seo-friendly, but would prefer to do this entirely in react. It would also be nice to have some way of implementing something like [getStaticProps in nextjs](https://nextjs.org/docs/basic-features/data-fetching/get-static-props) so that dynamic data can be fetched at build time.

**Comment by garronej** [comment]
> Follow-up: Is there a recommended approach for generating the initial HTML returned by keycloak?  

I don't think you can make Keycloak login pages SEO friendly.  
Login pages url includes queries parameters generated by the client, thoses expires quick.  

For example this is what a login link looks like:  
https://auth.lab.sspcloud.fr/auth/realms/sspcloud/protocol/openid-connect/auth?client_id=onyxia&redirect_uri=https%3A%2F%2Fdatalab.sspcloud.fr%2Fhome&state=c94eedfc-2394-48fe-8fb7-3997fa518c3e&response_mode=query&response_type=code&scope=openid&nonce=73e2e6e4-3320-48e5-90a8-8acebd3466b2&THEME_ID=onyxia&HEADER_ORGANIZATION=SSP%20Cloud&HEADER_USECASE_DESCRIPTION=Datalab&THERMS_OF_SERVICES=%7B%20%22en%22:%20%22https://www.sspcloud.fr/tos_en.md%22,%20%22fr%22:%20%22https://www.sspcloud.fr/tos_fr.md%22%20%7D%0A&ui_locales=en  

And if you don't have all theses parameters you get:  

<img width="1178" alt="image" src="https://user-images.githubusercontent.com/6702424/221969261-d3ccb5c1-854b-4471-be5d-dabf44d43391.png">

**Comment by lordvlad** [comment]
> Is there a recommended approach for generating the initial HTML returned by keycloak? I would like to be able to include html tags to make it more seo-friendly, but would prefer to do this entirely in react.

Is there a point to make a login page SEO friendly? Or do you intend to put content on the login page? Maybe try to turn your logic around and embed the login page in your other content page? (e.g. using an iframe WARNING this has security implications, act on your own peril https://stackoverflow.com/questions/60659225/how-to-have-keycloak-login-page-in-iframe)

**Comment by garronej** [comment]
Interesting!
