### ISSUE TITLE
Run keycloakify behind corporate proxy

### ISSUE THREAD

**Issue by boldt** [InseeFrLab/keycloakify#257]
If I run keycloakify behind a corporate proxy, I get the following error:

```
$ npx keycloakify
🔏 Building the keycloak theme...⌚
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT 140.82.121.3:443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1300:16)
Emitted 'error' event on ClientRequest instance at:
    at TLSSocket.socketErrorListener (node:_http_client:494:9)
    at TLSSocket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -4039,
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '140.82.121.3',
  port: 443
}

Node.js v18.11.0
```

### Note

The npm config vars `https-proxy`, `no-proxy` and `proxy` are set and work well for the dependency installation and within other projects.

**Comment by lordvlad** [comment]
the stack trace is a bit short, so its hard to figure out which command _exactly_ fails, but I have a hunch that its this call here

https://github.com/InseeFrLab/keycloakify/blob/main/src/bin/tools/downloadAndUnzip.ts#L69

It should be adapted to support proxies like this https://stackoverflow.com/a/6781592

@garronej I can take a swing at it some time next week

**Comment by garronej** [comment]
Hey @lordvlad,  
Thank you, that would be great 😀

**Comment by lordvlad** [comment]
@boldt I tested my implementation with squid proxy on localhost, let me know how it works for you

**Comment by garronej** [comment]
@boldt  6.12.7-rc.0 is available if you want to test

**Comment by garronej** [comment]
Life is too short, let's release, if it has problems we'll fix them.

**Comment by boldt** [comment]
`npx keycloakify@6.12.7-rc.0` still throws the error.

The release **6.13.0-rc.0** is not available via npm yet:

* https://www.npmjs.com/package/keycloakify?activeTab=versions

**Comment by garronej** [comment]
My bad! it's available now.

**Comment by boldt** [comment]
```
$ npx keycloakify@6.13.0-rc.0
npm ERR! code ETARGET
npm ERR! notarget No matching version found for keycloakify@6.13.0-rc.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

I still can't see it on npm: https://www.npmjs.com/package/keycloakify?activeTab=versions

**Comment by garronej** [comment]
sorry for all the back en forth, I don't understand what whent up with the CI.  
Anyway, it's available for real this time: https://www.npmjs.com/package/keycloakify/v/6.13.0-rc.0

**Comment by boldt** [comment]
That version works. Thanks!

**Comment by garronej** [comment]
Great thank you for the feedback, I'll release then
