### ISSUE TITLE
Provide custom variables inside authentication pages

### ISSUE THREAD

**Issue by efthimispegas** [InseeFrLab/keycloakify#258]
I am developing keycloak themes for a multibranch project and there's been a need for support of external links to client hosted domain urls inside the keycloak themed pages (login, update password etc.). The idea is to be able to navigate to external links that are provided via some kind of context variable (like the ones provided via kcContext for login). Is there a possible way to pass external urls to kcContext and then consume them inside the react app?

**Comment by garronej** [comment]
Yes!  
You can do that by passing variables to the URL before redirecting: https://docs.keycloakify.dev/context-persistence  
Or maybe you want to defines thoses variables in the Keycloak administration panel?

**Comment by garronej** [comment]
I mean it's a bit hacky but you can use the realm display name to pass whatever you want to your theme:  

<img width="1470" alt="image" src="https://user-images.githubusercontent.com/6702424/223112812-6695ed61-c663-4e08-914b-2e6d891adbfd.png">


<img width="1617" alt="image" src="https://user-images.githubusercontent.com/6702424/223112724-7b779988-f1f9-422c-a918-0aefc4474e3c.png">

**Comment by efthimispegas** [comment]
Got it! Thanks
