### ISSUE TITLE
Some pages are not exported from v2

### ISSUE THREAD

**Issue by erikdstock** [InseeFrLab/keycloakify#26]
I'm trying to adopt keycloakify with my own theme library by re-implementing `KcApp`, importing all pages and  incrementally substituting my own template and page components. However with the v2 upgrade (I had just gotten this working for v1 when v2 was released) `LoginOtp`, `Register` and `Terms` are not exported. Is this an oversight, or is something not working for them?

**Comment by garronej** [comment]
Hi @erikdstock, yes it is an oversight thank you for reporting.
However you can import them even if they are not exported defaults, see [here](https://github.com/InseeFrLab/onyxia-web/blob/236339020dd359ab4e7c46dddb24fc9ff7e68dbb/src/app/components/KcApp/KcApp.tsx#L14)

**Comment by erikdstock** [comment]
Yep, thanks! That's actually what i'm doing, just wanted to be sure I wasn't missing a bigger issue.
