### ISSUE TITLE
Apply theme to unexpected error

### ISSUE THREAD

**Issue by Rafael-Ramblas** [InseeFrLab/keycloakify#265]
Hi there! First of all, I want to thank you for creating such an awesome library.

I'm currently working on implementing a custom error page for unexpected errors, such as when users try to log in to realms and clients that don't exist. However, I've noticed that the `error.ftl` page doesn't seem to work in these cases.

I've checked the `window` object in the console and it appears that there's no `kcContext` there. My question is whether Keycloakify has support for this kind of scenario. If not, could you please provide some guidance on how to implement this?

Here are a couple of examples of the errors I'm encountering:

When trying to log in to a non-existent realm: `realms/not-valid/login-actions/authenticate?client_id=default` (resulting in a 404 error)
When trying to log in to a non-existent client within a realm: `realms/myrealm/login-actions/authenticate?client_id=not-valid` (resulting in a 400 error)

Thanks in advance for your help!

**Comment by garronej** [comment]
Hello @Rafael-Ramblas,  

Thank for the kind words,  

The error pages you are getting when it's a non exsisting realm/client is the `error.ftl` of the account theme, not the login theme.  
In the current iteration of Keycloakify it's not possible to customize the account theme ( see: https://docs.keycloakify.dev/limitations#login-and-email-only )  
But in Keycloakify v7 it will be possible and Keycloakify v7 is just around the corner, it should be released in a couple of days.

**Comment by Rafael-Ramblas** [comment]
Thanks for the quick response!
Wonderful to hear this, I will be waiting for v7

**Comment by garronej** [comment]
@Rafael-Ramblas,  
I'm very sorry, I think I got this wrong.  
I don't know from where error page that you are seeing when the realm/client id isn't correct come from or if it is customisable.  

If I where you I'd ask on the Keycloak repo or in their discourse.  
Let me know what they said.

**Comment by Rafael-Ramblas** [comment]
@garronej 
In order to theme the page `realms/not-valid/login-actions/authenticate?client_id=default`, the keycloakify generated theme needs to be selected in the master's realm login theme. For the page `realms/myrealm/login-actions/authenticate?client_id=not-valid` the realm's login theme should be setted too.

**Comment by garronej** [comment]
Thanks for the feedback!  
That's right, I've updated the output of the `npx keycloakify` command.
