### ISSUE TITLE
Feature Request: Improve Login Typings 

### ISSUE THREAD

**Issue by willwill96** [InseeFrLab/keycloakify#273]
Currently, `rememberMe` is typed as a boolean, however, in the cases, I've seen it is actually a string, (`"on"` in the case of being checked).

Keycloak also seems to only treat `rememberMe` as true if the value is `"on"`. [ref](https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/authentication/authenticators/browser/AbstractUsernameFormAuthenticator.java#L210)

Additionally, it seems that keycloak will also return the attempted password on failed attempts, which could be useful to pre-populate the form on errors:
![image](https://user-images.githubusercontent.com/10997562/226787279-dbfafacc-8c03-4498-97a5-40a4d49e3732.png)

I created a PR here with the changes I am suggesting:
https://github.com/InseeFrLab/keycloakify/pull/272

**Comment by garronej** [comment]
Thanks you!
