### ISSUE TITLE
How can we use custom styles in KcApp?

### ISSUE THREAD

**Issue by ialisyed** [InseeFrLab/keycloakify#31]
Hello,

Could you please provide some documentation that how can we add our custom styles?

I have tried many ways using `useStyles` of `tss-react` and styling of material/ui but whenever I run app keycloak, page does not render and says that `Refused to apply styles`.

I would be grateful if you can provide a guide to customize styles.

Thanks

**Comment by garronej** [comment]
Hi,  
I am currently upgrading the version of `tss-react`.  
What version of `@material-ui` are you using? v5 or v4?

**Comment by ialisyed** [comment]
I am using v4

**Comment by garronej** [comment]
`Refused to apply styles` happens when you have the wrong MIME type.   
Usually it means that the url of the `.css` file is broken.
Try copy pasting the url from the error message into your chome search bar. What do you get?

**Comment by ialisyed** [comment]
Is the latest version of keycloakify compatibale with `@material-ui` v5?

**Comment by garronej** [comment]
Yes

**Comment by garronej** [comment]
Just have a look at the [quick start](https://github.com/garronej/tss-react) of `tss-react`.

![image](https://user-images.githubusercontent.com/6702424/130614261-49a4fce4-9c8b-4c53-b3b2-17bfa16694a8.png)

**Comment by ialisyed** [comment]
Thanks @garronej !
