### ISSUE TITLE
[QS] How to use kcContext for custom implementation

### ISSUE THREAD

**Issue by shubhamdeodia** [InseeFrLab/keycloakify#33]
First of all thanks a lot for creating this package, it might just be a lifesaver for people like us.

I am trying to make use of keycloakify with custom Material UI login screen.

From the source code, I can see that in the example template, you have created your own [login page](https://github.com/InseeFrLab/keycloakify/blob/main/src/lib/components/Login.tsx)

I see in this login page you are making use of `kcContext`, which help maintain the values state.

Is there any documentation on how to use `kcContext` for any custom implementation. If not can you guide me in the right direction and I will more than happy make it possible.

Appreciate your help.

**Comment by garronej** [comment]
Hi!
I don't know if you know how things are done in FreeMarker but kcContext the kcContext is a JavaScript object containing the values made avalible to you by Keycloak to construct the page on the backend using FTL.
If you are feeling a bit lost I'll suggest you play around with the templates I created. 
You can also inspect the login page of this app: https://onyxia.sspcloud.fr, have a look at Windows.kcContext in the developer console for example an see how the values are used in the page.
I hope it helps

Regards

**Comment by garronej** [comment]
> From the source code, I can see that in the example template, you have created your own login page

And btw this is not a creation per say, it's a direct react translation of this [login.ftl](https://github.com/keycloak/keycloak/blob/11.0.3/themes/src/main/resources/theme/base/login/login.ftl)

**Comment by garronej** [comment]
Infact what this library does is it render page on the frontend instead of the backend.

**Comment by mRamzii** [comment]
@shubhamdeodia It's actually very simple to implement, as @garronej mentionned, you are just rendering the page with react, and your context has everything you need to create custom pages.

That is exactly what I did, fully customized React pages for my website, just grab a hold of the {url, login, register ...} in the KcContext, and use them to submit forms to interact with Kc, just like Kc does

**Comment by garronej** [comment]
@mRamzii I am curious to see results. Would you share the link ?

**Comment by mRamzii** [comment]
@garronej Hello,

Of course, the application is not Online yet, but soon will be, I'll make sure to share the links with you.

Thanks

**Comment by shubhamdeodia** [comment]
@garronej : I followed the steps which you have provide [here](https://github.com/garronej/keycloakify-demo-app)

I copied the generated jar to` /keycloak/current/standalone/deployment`

On the keycloak server, I am seeing this error: 
```
WFLYDS0014: Scan found content configured for auto-deploy that could not be safely auto-deployed. See details above. Deployment changes will not be processed until all problematic content is either removed or whether to deploy the content or not is indicated via a .dodeploy or .skipdeploy marker file. Problematic deployments are [keycloak-theme.jar]
```

Am i doing something wrong, I believe these the are accurate steps which I followed.

one odd thing which I noticed in the generated pom.xml, it is having 
```
<groupId>there.was.no.homepage.field.in.the.package.json.keycloakify-demo-app.keycloak</groupId>
```

is homepage field, mandatory to make it work ?

**Comment by garronej** [comment]
Hi @shubhamdeodia,  
I saw you just deleted your last message, I assume you found a solution.  

However I wanted to touch on the fact that, no, homepage isn't mandatory. It is used for an optimisation that consist in allowing the static files not to be served from keycloak. It is documented [here](https://github.com/InseeFrLab/keycloakify#enable-loading-in-a-blink-of-an-eye-of-login-pages----external-assets). Even if it do provides a significant performance boost in some configurations, it is hard to set it up so i'll suggest not to bother for now.

**Comment by shubhamdeodia** [comment]
@garronej : Thanks you.

So I just followed all the steps and I am able server a custom login page built in react in keycloak.

Although, on the UI it seems to be working fine. But this is error I am getting in server logs.

So I am not using the template wrapper component, as for some reason it doesn't work at all. 

Is there anything i could do to keep my logs clean ?

```
FTL stack trace ("~" means nesting-related):
        - Failed at: #local value = object[key]  [in template "login.ftl" in macro "objectToJson" at line 70, column 21]
        - Reached through: @compress  [in template "login.ftl" in macro "objectToJson" at line 36, column 5]
        - Reached through: @objectToJson object=value depth=(dep...  [in template "login.ftl" in macro "objectToJson" at line 81, column 27]
        - Reached through: @compress  [in template "login.ftl" in macro "objectToJson" at line 36, column 5]
        - Reached through: @objectToJson object=(.data_model) de...  [in template "login.ftl" at line 163, column 43]
  ```

**Comment by garronej** [comment]
Hi @shubhamdeodia,  

I am sorry, no these logs are normal and there is no way I know of to do things differently so they do not appear.  
I should update the readme about that though.

**Comment by garronej** [comment]
I added [a section in the README](https://github.com/InseeFrLab/keycloakify#about-the-errors-related-to-objecttojson-in-keycloak-logs) about the errors in the Keycloak logs.

**Comment by shubhamdeodia** [comment]
@garronej : Thank for all the help.

One last qs though, Do you know how can we handle MFA scenario where we need to display QR code on login screen.

**Comment by mRamzii** [comment]
@shubhamdeodia You can set the authentication flow on the realm to require OTP, then add a custom page "login-config-totp.ftl"

You can take the base page [https://github.com/keycloak/keycloak/blob/master/themes/src/main/resources/theme/base/login/login-config-totp.ftl](here) as an example and implement it in React.

Also checkout the part where you need to declare custom pages for types in TS.
