### ISSUE TITLE
Redirect after login?

### ISSUE THREAD

**Issue by cindy-choi** [InseeFrLab/keycloakify#37]
Hi. :)

Is there any way to redirect origin page after login?
My application stays on the login page after successful login.

I tried 2 different ways to login.

1. with axios
```
    const handleLogin = async () => {
      await api.login({url: url.loginAction, userName: userName, password: password, });

      // go back to home page!
    };
````

2. with form & submit button
```
<form
    method="post"
    action={url.loginAction}
>
...
</form>
```

**Comment by garronej** [comment]
Hi @cindy-choi,  
You should specify the redirect when you first call the `.login()` method from [the official adapter](https://www.npmjs.com/package/keycloak-js).  

Example: https://www.npmjs.com/package/keycloak-js

**Comment by garronej** [comment]
Sorry my link was dead. Did manage to solve your issue?

**Comment by garronej** [comment]
I close but don't hesitate to reach if you need futher assistance.

**Comment by cindy-choi** [comment]
> Sorry my link was dead. Did manage to solve your issue?

I found available link from your older link, It works! ;)
Sorry to late, keycloakify is of great help to me. thanks.
