### ISSUE TITLE
New register page ?

### ISSUE THREAD

**Issue by olevitt** [InseeFrLab/keycloakify#38]
Hi,

We are upgrading from keycloak 11 to 15 and noticed that the register page was customized anymore.  
From my limited keycloak understanding, it seems there is a new `register-user-profile.ftl` page. See https://github.com/keycloak/keycloak/blob/master/themes/src/main/resources/theme/base/login/register-user-profile.ftl  
Could it be related ?

**Comment by garronej** [comment]
It's on the go
