### ISSUE TITLE
Support OTP

### ISSUE THREAD

**Issue by htekgulds** [InseeFrLab/keycloakify#4]
Thank you for this life saving project!

How can we customize the otp one time code page?

Regards

**Comment by garronej** [comment]
Hi,

Thank you for the kind word,

It's not implemented yet 😬 

It's no big deal I just need to convert this file:

![image](https://user-images.githubusercontent.com/6702424/116760897-860e0400-aa16-11eb-95ab-29abc7ed634f.png)

into a react component.  

If you are in a hurry you can do in and submit a PR,
otherwise you can wait until I do it. 

Best regard

**Comment by htekgulds** [comment]
Hello,

I actually tried to do that as well. Created a component and added to my custom KcApp as another `case` line. But it didn't generate a login-otp.ftl file so I'm guessing I needed something else implemented.

``` javascript
export const KcApp = memo(({ kcContext, ...props }) => {
  switch (kcContext.pageId) {
    ***
    case "terms.ftl": return <Terms {...{ kcContext, ...props }}/>;
    case "login-otp.ftl": return <LoginOTP {...{ kcContext, ...props }}/>; // here is the new line
    default: return null;
  }
})
```

If you could point me in the right direction I would be glad to help 😄

Best Regards

**Comment by garronej** [comment]
Yeah,
You did your part. I need to do mine for it to work,the ftl values need to be converted into a js object. 
I will do it today

**Comment by htekgulds** [comment]
Thanks a lot! Looking forward to it

Best Regards

**Comment by garronej** [comment]
@htekgulds Seems to be working

![image](https://user-images.githubusercontent.com/6702424/116785084-f90b8f00-aa97-11eb-99a2-3861afe7a9c3.png)

Haven't the time to test in-depth though. Let me know if there is any issue.

**Comment by htekgulds** [comment]
OK thank you!

Also the missing page guide looks great! Hopefully I wont be bothering you as much in the future 😅 

Best Regards

**Comment by garronej** [comment]
@htekgulds You are welcome,

I would be happy to see the result of what you are working on when your are done if you want to share it with me.  

Out of curiosity, where did you find this project.

**Comment by htekgulds** [comment]
Ofcourse! I'm just customizing the pages using some bootstrap template so it made sense to rewrite them as opposed to fiddling with classes 😅 

I googled react keycloak login theme and found your article on dev.to https://dev.to/garronej/keycloakify-create-keycloak-themes-using-react-5b89😄 Lucky!
