### ISSUE TITLE
i18n.currentLanguageTag not being updated

### ISSUE THREAD

**Issue by koo27** [InseeFrLab/keycloakify#412]
I'm using keyloackify starter and trying to change language following [the docs](https://docs.keycloakify.dev/adding-text-keys)
In App.tsx there is `getUiLocales: () =>` that should pass ui_locales as query parameter to the login page, and it does.
But in the login page the `i18n.currentLanguageTag` is always "en" and the `locale` from `kcContext` is undefined

**Comment by garronej** [comment]
Hi @koo27,  
The localisation needs to be enabled on your Keycloak realm.  
It's not enabled by default.  
Look in the realm settings in Keycloak admin panel.

**Comment by garronej** [comment]
I should mention it in the doc

**Comment by koo27** [comment]
Yes it would be useful for someone that is using keycloak for the first time :)
By the way, the i18n you extended accepts only strings right?
It would be very useful to accept json as well.
Something like
```
en: {
    login: {
        title: "login title",
        username: "Username"
    }
}
```
