### ISSUE TITLE
Alternative theme source directories

### ISSUE THREAD

**Issue by rome-user** [InseeFrLab/keycloakify#429]
Hi,

I am trying to migrate a Keycloakify v6.13.1 project to v8, but I seem to be stuck at a new requirement. After updating the version, running `npx keycloakify` produces the following error.

```
Building the keycloak theme...
Can't locate your theme source directory. It should be either: 
src/ or src/keycloak-theme.
Example in the starter: https://github.com/keycloakify/keycloakify-starter/tree/main/src/keycloak-theme
```

My directory structure is like so:

```
src
└── appname
    └── keycloak
        ├── theme
        │   └── login.css
        └── theme.cljs
```

It's a very simple standalone project that makes use of `KcApp` component together with `defaultKcProps` and the `useI18n` hook. This is a ClojureScript project with a single namespace `appname.keycloak.theme`. 

I am fine with having to reorder the project structure, but ClojureScript does not allow hyphens in directory names. Would it be possible to allow a theme source folder named `keycloak_theme` or even a custom path to the theme source directory?

**Comment by garronej** [comment]
Hi @rome-user,  

Sure, I can allow `keycloak_theme`
but I think the problem is more that, now, you have to pute everything within a `login` directory since we now support account theme as well.  

Try:  

```raw
src
└── login
  └── appname
      └── keycloak
          ├── theme
           │   └── login.css
          └── theme.cljs
```
