### ISSUE TITLE
What changes should be made to make it work with custom webpack config.

### ISSUE THREAD

**Issue by shubhamdeodia** [InseeFrLab/keycloakify#47]
Is there any specific guide to make it work with custom webpack config.

When I tried it is just tries to find the bundle.js on the keycloak domain and gives 404 error.

Any suggestion, how can I fix it or using `create-react-app` is absolutely essential ?

**Comment by shubhamdeodia** [comment]
It works fine, we can close this ticket, Thanks for all the help.

**Comment by ddubrava** [comment]
Hi! What about these errors?

<img width="1728" alt="Screenshot 2023-07-24 at 14 25 38" src="https://github.com/keycloakify/keycloakify/assets/22116465/811ba3a4-6946-494d-928f-4d882537ce72">

<img width="1347" alt="Screenshot 2023-07-24 at 14 25 45" src="https://github.com/keycloakify/keycloakify/assets/22116465/0e7e657c-a2b9-45cf-99f9-f34b97b3226f">
