### ISSUE TITLE
Additional configuration options in the package.json

### ISSUE THREAD

**Issue by Ann2827** [InseeFrLab/keycloakify#49]
Hi!
I need to build several themes for different realms. But with the same components.
(I use my KcApp and pages components). I really don't want to duplicate the react app because of this.

Could you add more customization options for the titles? For example:

*package.json:*
```json
{
  "other_props": "...",
  "keycloakify": {
    "themeName": "example",
    "sourcePath": "build",
    "buildPath": "build_keycloak2"
  }
}
```

*src/bin/build-keycloak-theme.ts:*
```ts
const parsedPackageJson: ParsedPackageJson = require(pathJoin(reactProjectDirPath, "package.json"));

const buildDirName: string = (parsedPackageJson as any)["keycloakify"]?.["buildPath"] ?? 'build_keycloak';
export const keycloakThemeBuildingDirPath = pathJoin(reactProjectDirPath, buildDirName);

...

const reactDirName: string = (parsedPackageJson as any)["keycloakify"]?.["sourcePath"] ?? 'build';
const themeName = sanitizeThemeName((parsedPackageJson as any)["keycloakify"]?.["themeName"] ?? parsedPackageJson.name);

...

"reactAppBuildDirPath": pathJoin(reactProjectDirPath, reactDirName),
```

**Comment by garronej** [comment]
Hi @Ann2827,  

I assume that the project you are working on isn't opensource but it would help a lot if you could setup a minimal repo to help me understand your use case. 
As your described it I don't see why we would need `"themeName"` when updating the `"name"` field of the `package.json` would do the trick.  
Same for `""buildPath"` wouldn't it be enough to `keycloakify && mv build_keycloak build_keycloak2`?  
 
I'm sure once I see it, it will click but I need to understand a feature request before implementing it.  

Best
