### ISSUE TITLE
Adding custom field to user attributes and registration form

### ISSUE THREAD

**Issue by nvegater** [InseeFrLab/keycloakify#50]
Hi, first of all thank you for this amazing project. I agree with all your motivations :).

Which branch is the right one for me to start ?

- I have a keycloak server already running.
- I want to add a custom theme extending "keycloak" theme  
- Add a select field to the registration form to add a custom user attribute.

"look_and_feel" branch ? 
demo branch ?

I started with the "look_and_feel" following "advanced usage" following this [guide](https://github.com/garronej/keycloakify-demo-app/tree/look_and_feel#keycloak-theme-only).

`Replaces those lines by const kcContext = realKcContext ?? kcContextMocks.kcLoginContext;, now if you run yarn start you will be able to debug the login page, replace kcLoginContext by kcRegisterContext and the register page will be loaded instead.`

This point doesnt apply for the code of the "look_and_feel" branch though. 

You see my confusion ? Otherwise let me know and I can try to explain it in other way :) 

Thank you!

**Comment by garronej** [comment]
Sorry, I don't have time to look at your issue in depth now but I just want to tell you that, as for right now the pattern validation in user attribute is broken.  
I hope to fix it today but just in case you'd run against a brick wall...;

**Comment by nvegater** [comment]
Thanks for answering. 

I just deployed a custom attribute select field like [this](https://wjw465150.gitbooks.io/keycloak-documentation/content/server_development/topics/custom-attributes.html). I'll let you know if that works :)

**Comment by garronej** [comment]
Oh yeah this will definitely work.  
We used to do that with email if I am not mistaking. 
Checkout [that](https://github.com/InseeFrLab/keycloakify#email-domain-whitelist) (and [that](https://github.com/garronej/keycloakify-demo-app/blob/de61901f310e0aa5e30af6d7be7528111c8d0713/src/KcApp/kcContext.ts#L35-L43) for testing outside of keycloak).  
But we gave up this approach in favour of the newer and greater "user attribute" feature:  

<p align="center">
    <a href="https://github.com/InseeFrLab/keycloakify/releases/download/v0.0.1/keycloakify_fontend_validation.mp4">
        <img src="https://user-images.githubusercontent.com/6702424/138880146-6fef3280-c4a5-46d2-bbb3-8b9598c057a5.gif">
    </a>
</p>

[ref](https://github.com/InseeFrLab/keycloakify/blob/main/README.md#user-profile-and-frontend-form-validation)  
  
The intefration of this Keyclaok feature is what's I am saying is half broken still. But I will fix it asap!
