### ISSUE TITLE
Implement login-update-password.ftl

### ISSUE THREAD

**Issue by ilkou** [InseeFrLab/keycloakify#51]
Hello,

There are no implementations for some pages, such as [login-update-password.ftl](https://github.com/keycloak/keycloak/blob/main/themes/src/main/resources/theme/base/login/login-update-password.ftl)

I think it'd be better if we can inject our implementations dynamically, for example:

```javascript
switch (kcContext.pageId) {
...
      case 'login-update-password.ftl':
           return <LoginUpdatePassword {...{ kcContext, ...kcProps }} />;
...
}
```

 => the library would build the `login-update-password.ftl` file

**Comment by garronej** [comment]
Hi @ilkou,  
I think what you describe is already possible, checkout [the relevant readme section](https://github.com/InseeFrLab/keycloakify#some-pages-still-have-the-default-theme-why)

**Comment by na-ji** [comment]
> Hi @ilkou, I think what you describe is already possible, checkout [the relevant readme section](https://github.com/InseeFrLab/keycloakify#some-pages-still-have-the-default-theme-why)

Hello !

I have a question that's not documented: how do you find the context that those pages will receive? For instance I found that the page `login-update-password.ftl` receive a `username` prop that should be added to the form. But to find that I had to log the context and build the theme to check. It there another way? 

With this knowledge, I think it will be much easier to implement the missing pages with correct mocking.

Thanks.

**Comment by ilkou** [comment]
@na-ji Hello !

for the existing pages, you can always check the [KcContextBase.ts](https://github.com/InseeFrLab/keycloakify/blob/main/src/lib/getKcContext/KcContextBase.ts#L27) file.

for other pages, I check the official [keycloak](https://github.com/keycloak/keycloak/blob/main/themes/src/main/resources/theme/base/login/login-update-password.ftl) implementation

There might be a better way to do it though, I hope that I've helped u somehow.

**Comment by garronej** [comment]
Hi @na-ji,  

I don't have this knowledge myself.  

For defining the type definitions I do what @ilkou suggest. I infer from usage looking at the official implementation.
