### ISSUE TITLE
ios Invalid regular expression: invalid group specifier name

### ISSUE THREAD

**Issue by stephane-segning** [InseeFrLab/keycloakify#53]
Hello! I'm using your tool and it's currently in production and I have a major issue on iOS (15). As the title says, I'm getting this error here when I uses it on iOS: `Invalid regular expression: invalid group specifier name`.

![image](https://user-images.githubusercontent.com/26783557/143506539-336420f3-d4a0-4ef4-80ce-e0727e67706a.png)

This only happens on iOS and only when I import something from `keycloakify`. Any help would be appreciated.

**Comment by garronej** [comment]
Sorry about that. I believe the issue have been fixed in the latest release.

**Comment by stephane-segning** [comment]
Hello, it worked. Thank you very much. I'm closing this.
