### ISSUE TITLE
"Bundler not supported" error despite using Webpack

### ISSUE THREAD

**Issue by rome-user** [InseeFrLab/keycloakify#535]
I currently have a project using Keycloakify v9.0.0. The layout is as follows
```
src
└── project
    ├── keycloak_theme
    │   └── login
    |   └── ...
    ...
```
The project uses Shadow CLJS, configured so that the compiler emits ESM code and Webpack handles bundling. (Details here: https://shadow-cljs.github.io/docs/UsersGuide.html#js-provider-external )

After upgrading to the latest version of Keycloakify (v9.4.2), I see the following error in the browser console. This is for the login page.

```
Uncaught Error: Bundler not supported
    BASE_URL            webpack://project/./node_modules/keycloakify/lib/BASE_URL.js?:43
    <anonymous>         webpack://project/./node_modules/keycloakify/lib/BASE_URL.js?:44
    js                  http://localhost:5000/static/js/libs.js:502
    __webpack_require__ http://localhost:5000/static/js/libs.js:2313
    <anonymous>         webpack://project/./node_modules/keycloakify/login/kcContext/kcContextMocks.js?:11
    ...
```

This problem occurs for both dev and production builds. The dev configuration looks like so.

```js
const webpack = require("webpack");
const path = require("path");

module.exports = {
  target: "web",
  mode: "development",
  entry: "./build/index.js",
  output: {
    path: path.resolve(__dirname, "build/static/js"),
    filename: "libs.js"
  },
  plugins: [
    new webpack.ProvidePlugin({
      process: "process/browser"
    })
  ]
};
```

**Comment by garronej** [comment]
Hello @rome-user,  

Thanks for reporting.  
Try with the latest version and tell me if it fixes it.

**Comment by garronej** [comment]
great!
