### ISSUE TITLE
no such file or directory, scandir 'E:\keycloak_custom\my-app\build_keycloak\src\main\resources\theme\my-app\tmp_xxKdLpdIdLd\keycloak\login\resources'

### ISSUE THREAD

**Issue by kousherAlam** [InseeFrLab/keycloakify#54]
```
Error: ENOENT: no such file or directory, scandir 'E:\keycloak_custom\my-app\build_keycloak\src\main\resources\theme\my-app\tmp_xxKdLpdIdLd\keycloak\login\resources'
    at Object.readdirSync (node:fs:1390:3)
    at crawlRec (E:\keycloak_custom\my-app\node_modules\keycloakify\bin\tools\crawl.js:41:39)
    at crawl (E:\keycloak_custom\my-app\node_modules\keycloakify\bin\tools\crawl.js:61:9)
    at transformCodebase (E:\keycloak_custom\my-app\node_modules\keycloakify\bin\tools\transformCodebase.js:48:50)
    at generateKeycloakThemeResources (E:\keycloak_custom\my-app\node_modules\keycloakify\bin\build-keycloak-theme\generateKeycloakThemeResources.js:124:51)
    at main (E:\keycloak_custom\my-app\node_modules\keycloakify\bin\build-keycloak-theme\build-keycloak-theme.js:57:73)
    at Object.<anonymous> (E:\keycloak_custom\my-app\node_modules\keycloakify\bin\build-keycloak-theme\index.js:17:37)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32) {
  errno: -4058,
  syscall: 'scandir',
  code: 'ENOENT',
  path: 'E:\\keycloak_custom\\my-app\\build_keycloak\\src\\main\\resources\\theme\\my-app\\tmp_xxKdLpdIdLd\\keycloak\\login\\resources'
}
```

**Comment by garronej** [comment]
On Windows you'll have to use [WSL](https://docs.microsoft.com/en-us/windows/wsl/install-win10).

are you?

**Comment by kousherAlam** [comment]
hi @garronej thank you for your response, 
Yes, I'm using WSL on my pc, also, docker was running while I was performing the operation.

**Comment by garronej** [comment]
Ok bummer,  
Are you using create-react-app?  
Could you please try to build [the demo project](https://github.com/garronej/keycloakify-demo-app) and tell me if it work?

**Comment by kousherAlam** [comment]
Hi, i run the demo project and got this error 
![image](https://user-images.githubusercontent.com/14360099/143813702-42a65b91-8912-4598-a415-54d26063ec63.png)

**Comment by garronej** [comment]
@kousherAlam This is what you get when it's working:  

![image](https://user-images.githubusercontent.com/6702424/143877900-423f6010-c571-4d57-871e-1cdc8e3d0a81.png)

**Comment by kousherAlam** [comment]
Hi @garronej , I still get the error, and as you can see, 34.8M is downloaded properly 

![image](https://user-images.githubusercontent.com/14360099/144446165-2259704f-a189-4445-9841-6af532332148.png)

**Comment by garronej** [comment]
okay, this is something else then... 

Is it you that submited this request for help on the keycloak comunity server ? 

![image](https://user-images.githubusercontent.com/6702424/144451963-a59884d4-efd5-4dc6-b6e8-2a9d3daf13b7.png)

**Comment by kousherAlam** [comment]
No not me bro.

But did you guys solved this issue ??

**Comment by garronej** [comment]
I am currently setting up a Windows Dev environment to try reproduce the issue

**Comment by garronej** [comment]
Can't reproduce. It work on my machine.
![image](https://user-images.githubusercontent.com/6702424/144469699-4a47b42a-1a5b-44cf-be1b-29ca74d61aac.png)
![image](https://user-images.githubusercontent.com/6702424/144470062-372211a2-9568-4eef-9e6d-addea10d7c3e.png)
![image](https://user-images.githubusercontent.com/6702424/144470208-fb1103e7-3a44-4a0a-8aec-fc22a62a9713.png)

**Comment by garronej** [comment]
@kousherAlam damn,  
I didn't notice but you have backslashes (`\`) in the screen shot you shared with me!!!  
This means that node for windows is running instead of node for linux.  
Are you sure you are using WSL and not cygwin?
I am not familiar with WSL but maybe you haven't installed node for your ubuntu and it's faling back to node for windows.  
Anyway you need to install node and yarn for linux:  

```bash
curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash -
sudo apt-get install -y nodejs
npm install --global yarn
```

Then

```bash
rm -rf node_modules
yarn
yarn keycloak
```

**Comment by kousherAlam** [comment]
Hi, @garronej 

You were right, now it's successfully building the demo app. 

Thanks for your help bro.

**Comment by garronej** [comment]
@kousherAlam no problem!  

If I may ask, would you follow me on github? I need to reach 100 follower.

If you do, thank you!

**Comment by garronej** [comment]
That's a [create-react-app issue](https://github.com/facebook/create-react-app/issues/11756)

**Comment by bakh4966** [comment]
> @kousherAlam damn, I didn't notice but you have backslashes (`\`) in the screen shot you shared with me!!! This means that node for windows is running instead of node for linux. Are you sure you are using WSL and not cygwin? I am not familiar with WSL but maybe you haven't installed node for your ubuntu and it's faling back to node for windows. Anyway you need to install node and yarn for linux:
> 
> ```shell
> curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash -
> sudo apt-get install -y nodejs
> npm install --global yarn
> ```
> 
> Then
> 
> ```shell
> rm -rf node_modules
> yarn
> yarn keycloak
> ```

When I run 'npm install --global yarn' I get this: node: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by node)... Could you please help me!

**Comment by bakh4966** [comment]
> ```shell
> npm install --global yarn
> ```

Hey @garronej 

![image](https://user-images.githubusercontent.com/22908130/201582309-fc23dc33-b6e0-4f84-a0fc-0a9c5a6f15f2.png)

for the advanced app I'm having this error, could you plz help me?

**Comment by garronej** [comment]
Hi @bakh4966,  

I'll need more info, your screen shot is cropped I can't see the relevent part.  
And please open another ticket.

**Comment by jophuijbers-wf** [comment]
I have this issue as well. I am trying to set up a keycloak theme, using the [starter project](https://github.com/keycloakify/keycloakify-starter). Isn't this just supposed to work on Windows? I don't understand why you need to run the yarn commands in Linux. 

```
yarn install v1.22.19
success Already up-to-date.
$ copy-keycloak-resources-to-public
node:fs:1527
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, scandir 'C:\Wefabricate\Projects\keycloakify-starter\public\keycloak-resources\tmp_suLeKsxId_c5f68d7a\keycloak\account\resources'
    at Object.readdirSync (node:fs:1527:3)
    at crawlRec (C:\Wefabricate\Projects\keycloakify-starter\node_modules\keycloakify\bin\tools\crawl.js:43:35)
    at crawl (C:\Wefabricate\Projects\keycloakify-starter\node_modules\keycloakify\bin\tools\crawl.js:65:5)
    at transformCodebase (C:\Wefabricate\Projects\keycloakify-starter\node_modules\keycloakify\bin\tools\transformCodebase.js:52:50)
    at C:\Wefabricate\Projects\keycloakify-starter\node_modules\keycloakify\bin\keycloakify\generateTheme\downloadKeycloakStaticResources.js:107:63
    at step (C:\Wefabricate\Projects\keycloakify-starter\node_modules\keycloakify\bin\keycloakify\generateTheme\downloadKeycloakStaticResources.js:56:23)
    at Object.next (C:\Wefabricate\Projects\keycloakify-starter\node_modules\keycloakify\bin\keycloakify\generateTheme\downloadKeycloakStaticResources.js:37:53)
    at fulfilled (C:\Wefabricate\Projects\keycloakify-starter\node_modules\keycloakify\bin\keycloakify\generateTheme\downloadKeycloakStaticResources.js:28:58) {
  errno: -4058,
  syscall: 'scandir',
  code: 'ENOENT',
  path: 'C:\\Wefabricate\\Projects\\keycloakify-starter\\public\\keycloak-resources\\tmp_suLeKsxId_c5f68d7a\\keycloak\\account\\resources'
}
```
