### ISSUE TITLE
Easiest way to make it work with next.js?

### ISSUE THREAD

**Issue by Powersource** [InseeFrLab/keycloakify#6]
From reading this issue https://github.com/InseeFrLab/keycloakify/issues/5 it sounds like this project is pretty tied to create-react-app. Unfortunately for me the app I'm working on is using (normally ssr'd) next.js. I'm no next.js pro yet so I'll have to think about how to make this work a bit. Do you have any ideas?

**Comment by garronej** [comment]
Hi @Powersource,  
Keycloakify will only ever work with apps that can be statically served (SPA). We can't ask Keycloak to render pages using node.   
What, I think , would be the better approach in your case would be to start a create-react-app project that would be only dedicated to your Keycloak theme and to externalize the design system you are using in your main app to be able to re-use it in the login.  

Hold on, I am updating the tutorial...

**Comment by Powersource** [comment]
Thanks! Yeah was thinking something along those lines.

**Comment by garronej** [comment]
@Powersource [here](https://github.com/InseeFrLab/keycloakify#my-framework-doesnt-seem-to-be-supported-what-can-i-do) are the instructions as detailed as I could make it about how to get started.  

I hope it helps.

**Comment by Powersource** [comment]
Thanks. I'll consider this resolved for now.
