### ISSUE TITLE
Error executing build script with missing mvn context

### ISSUE THREAD

**Issue by willadsmith** [InseeFrLab/keycloakify#601]
**Hello! After running the build script in GitLab CI, an error with context was returned**

$ yarn keycloakify build
yarn run v1.22.22
$ /builds/project/infrastructure/keycloak/project-keycloakify-theme/node_modules/.bin/keycloakify build
🔏 Building the keycloak theme...⌚
node:internal/errors:984
  const err = new Error(message);
              ^
Error: Command failed: mvn clean install
    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at checkExecSyncError (node:child_process:890:11)
    at Object.execSync (node:child_process:962:15)
    at /builds/project/infrastructure/keycloak/project-keycloakify-theme/node_modules/keycloakify/bin/keycloakify/keycloakify.js:195:39
    at step (/builds/project/infrastructure/keycloak/project-keycloakify-theme/node_modules/keycloakify/bin/keycloakify/keycloakify.js:67:23)
    at Object.next (/builds/project/infrastructure/keycloak/project-keycloakify-theme/node_modules/keycloakify/bin/keycloakify/keycloakify.js:48:53)
    at fulfilled (/builds/project/infrastructure/keycloak/project-keycloakify-theme/node_modules/keycloakify/bin/keycloakify/keycloakify.js:39:58) {
  status: 1,
  signal: null,
  output: [
    null,
    Buffer(1622) [Uint8Array] [
       91,  73,  78,  70,  79,  93,  32,  83,  99,  97, 110, 110,
      105, 110, 103,  32, 102, 111, 114,  32, 112, 114, 111, 106,
      101,  99, 116, 115,  46,  46,  46,  10,  91,  73,  78,  70,
       79,  93,  32,  10,  91,  73,  78,  70,  79,  93,  32,  45,
       45,  60,  32, 100,  98, 112,  45, 107, 101, 121,  99, 108,
      111,  97, 107,  45,  98,  99,  99,  45, 100, 101, 115, 105,
      103, 110,  45, 116, 104, 101, 109, 101,  46, 107, 101, 121,
       99, 108, 111,  97, 107,  46, 107, 101, 121,  99, 108, 111,
       97, 107,  58, 100,
      ... 1522 more items
    ],
    Buffer(0) [Uint8Array] []
  ],
  pid: 262,
  stdout: Buffer(1622) [Uint8Array] [
     91,  73,  78,  70,  79,  93,  32,  83,  99,  97, 110, 110,
    105, 110, 103,  32, 102, 111, 114,  32, 112, 114, 111, 106,
    101,  99, 116, 115,  46,  46,  46,  10,  91,  73,  78,  70,
     79,  93,  32,  10,  91,  73,  78,  70,  79,  93,  32,  45,
     45,  60,  32, 100,  98, 112,  45, 107, 101, 121,  99, 108,
    111,  97, 107,  45,  98,  99,  99,  45, 100, 101, 115, 105,
    103, 110,  45, 116, 104, 101, 109, 101,  46, 107, 101, 121,
     99, 108, 111,  97, 107,  46, 107, 101, 121,  99, 108, 111,
     97, 107,  58, 100,
    ... 1522 more items
  ],

  stderr: Buffer(0) [Uint8Array] []
}
Node.js v20.16.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Cleaning up project directory and file based variables
00:00
ERROR: Job failed: command terminated with exit code 1

**Installed Apache Maven 3.9.6 and Node v 20.16.0**

<img width="450" alt="Снимок экрана 2024-08-01 в 18 25 11" src="https://github.com/user-attachments/assets/910ef2c6-7c59-4f44-b86d-7e8891702540">

**Comment by garronej** [comment]
And the project builds correctly locally?

**Comment by willadsmith** [comment]
@garronej Locally it runs normally, without errors. But in CI it doesn't run.

**Comment by garronej** [comment]
It's probably a network policy, you're not allowed to download from the maven central repository.  

But you're using an older version of Keycloakify.  
On the new version you can use [this option](https://docs.keycloakify.dev/build-options/xdg_cache_home) to build offline.  

You just need to dump the `node_modules/.cache/keycloakify` directory and upload it as an artefact in your CI to be able to build without needing a network connection.
