### ISSUE TITLE
Local Fonts not loading

### ISSUE THREAD

**Issue by marziman** [InseeFrLab/keycloakify#62]
Dear @garronej 

many thanks for the great project. We started using it for our project.

Can you please help us with the local fonts?
We can not load them from GoogleFonts or remote and they shall be there as local fonts.

I tried all your workarounds and it just didnt work. Can you please provide us guidance, which steps we have to do, to build the project and include in docker image with our local fonts? The KC docker image keeps ignoring them.

This would be so great. The links at workaround are not working anymore. 

Many thanks!

**Comment by garronej** [comment]
Hi @marziman,  

> many thanks for the great project.  

Thank you for the kind works.  

>  The links at workaround are not working anymore.  

Sorry for the broken README link. [It's fixed now](https://github.com/InseeFrLab/keycloakify#possible-workarounds)

There is always [the template repo](https://github.com/garronej/keycloakify-demo-app) that that you can refer to.  

Let me know if you have any more questions.  

Best

**Comment by marziman** [comment]
@garronej it worked!
Many thanks for your help. The links in readme with example template repo helped me to get it done.

BR Mehmet
