### ISSUE TITLE
logs about error in macro "objectToJson_please_ignore_errors" should be removed

### ISSUE THREAD

**Issue by miriampechman** [InseeFrLab/keycloakify#67]
FTL stack trace ("~" means nesting-related):
	- Failed at: #local value = object[key]  [in template "login.ftl" in macro "objectToJson_please_ignore_errors" at line 77, column 21]
	- Reached through: @compress  [in template "login.ftl" in macro "objectToJson_please_ignore_errors" at line 43, column 5]
	- Reached through: @objectToJson_please_ignore_errors ob...  [in template "login.ftl" in macro "objectToJson_please_ignore_errors" at line 88, column 27]
	- Reached through: @compress  [in template "login.ftl" in macro "objectToJson_please_ignore_errors" at line 43, column 5]
	- Reached through: @objectToJson_please_ignore_errors ob...  [in template "login.ftl" in macro "objectToJson_please_ignore_errors" at line 88, column 27]
	- Reached through: @compress  [in template "login.ftl" in macro "objectToJson_please_ignore_errors" at line 43, column 5]
	- Reached through: @objectToJson_please_ignore_errors ob...  [in template "login.ftl" in macro "objectToJson_please_ignore_errors" at line 88, column 27]
	- Reached through: @compress  [in template "login.ftl" in macro "objectToJson_please_ignore_errors" at line 43, column 5]
	- Reached through: @objectToJson_please_ignore_errors ob...  [in template "login.ftl" in macro "objectToJson_please_ignore_errors" at line 88, column 27]

**Comment by garronej** [comment]
Hi @miriampechman,  
Update Keycloakify, it have been fixed in latest release.

**Comment by miriampechman** [comment]
took the latest version, thanks!!!
