### ISSUE TITLE
Documentation out of date

### ISSUE THREAD

**Issue by Plawn** [InseeFrLab/keycloakify#71]
The documentation link pointing to the example source code with onyxia-ui are out of date, and I can't find the correct way to use your tool with material-ui v5 or v4. Can you point me in the correct direction ?

Thanks for your work !

**Comment by Plawn** [comment]
Looks like, it's changed repository: 

https://github.com/InseeFrLab/onyxia-web/blob/main/src/ui/components/KcApp/KcApp.tsx

**Comment by garronej** [comment]
I am fixing the links

**Comment by garronej** [comment]
All links have been fixed. Thanks for reporting.
