### ISSUE TITLE
using keycloakify

### ISSUE THREAD

**Issue by hamid842** [InseeFrLab/keycloakify#74]
Hi everyone,
I want to create a react app and start to customize keycloak themes that deployed somewhere.
actually I read a lot [this link](https://github.com/InseeFrLab/keycloakify), but confused. 
got error on "yarn keycloak" command.
I'd really appreciate if anyone could help.

**Comment by garronej** [comment]
Hi @hamid842,  
This would go in the [discussion section](https://github.com/InseeFrLab/keycloakify/discussions) of the repo.  
You should pass your error messages.  
I advise you to start with [the canonical demo project](https://github.com/garronej/keycloakify-demo-app) (by clicking on "use this template") and start hacking around from here.
