### ISSUE TITLE
useKcMessage doesn't work on safari

### ISSUE THREAD

**Issue by shubhamdeodia** [InseeFrLab/keycloakify#76]
I have been using this package extensively and its helping me a lot, So kudos to you for putting all the efforts.

I would like to raise issue for `useKcMessage` as it doesn't work on safari browser. The error is specifically on 

https://github.com/InseeFrLab/keycloakify/blob/2b331e76550fdeb8e1afc4fb8b6bf3e1a480b155/src/lib/i18n/useKcMessage.tsx#L31

and the error is

```
[Error] SyntaxError: Invalid regular expression: invalid group specifier name
	(anonymous function) (bundle.js:85364)
```
![image](https://user-images.githubusercontent.com/55275771/149669340-6378218a-b8d6-47ca-8076-98cef9c6ed5f.png)

On researching more this seems to be Safari specific issue

https://stackoverflow.com/questions/51568821/works-in-chrome-but-breaks-in-safari-invalid-regular-expression-invalid-group

Would really appreciate if you could help me fix it.

**Comment by garronej** [comment]
Hi @shubhamdeodia,  
Good news for you.
Unless I am mistaking, this issue have been fixed quite a long time ago.  
You just need to update keycloakify. 

Best

**Comment by garronej** [comment]
https://github.com/InseeFrLab/keycloakify/commit/604655c02d9cd5a7bdc80019e0c7a8ea93ffa962
