### ISSUE TITLE
How to use theme.properties

### ISSUE THREAD

**Issue by jpreecenb** [InseeFrLab/keycloakify#8]
Hello! Love the project!

I'm new to Keycloak and Keycloakify, so apologies if this is a simple question.

I'm working on migrating an existing Keycloak theme to use Keycloakify.  The existing theme is written using FTL.

The existing theme has variables in the FTL files like so;

```html
        <a name="Home" href="${primaryUrl}" title="${nameOfTitle}" data-ga-tracking-id="headerLogo">
```

My understanding is that these variables come from the `theme.properties` file.

How can I access these variables on the React side?

Thanks

**Comment by garronej** [comment]
Hi @jpreecenb, 
I will need a bit more context.  
Could you please copy past a bit more than just the line.

**Comment by garronej** [comment]
I need to see where `primaryUrl` and `nameOfTitle`.  
My guess is that they are iterations values from a loop over a custom theme property but they could also come from the data model. ..
Instructions about how to proceed will depend  on which case you are in.

**Comment by garronej** [comment]
I can't tell just by looking at the line

**Comment by garronej** [comment]
Ok, thanks for the detailed explanation,  
I will try to guide you in porting you theme to Keycloakify.  

The values in `theme.properties` correspond to [`kcProps`](https://github.com/InseeFrLab/keycloakify/blob/main/src/lib/components/KcProps.ts) in Keycloakify.  

You are in a situation where you want to re-write your ftl code into React components.  
You will then pass props to those components, that will correspond to the keys value you had in `theme.properties`.  

You will for example create a `<Header>` component that take a prop `awl_nameOfTitle ` and you will invoke it like this:  
`<Header awl_nameOfTitle="Ambrose Wilson" />`.  

Converting `.ftl` files into React is not rocket science.  
Check for example how I converted [`login.ftl`](https://github.com/keycloak/keycloak/blob/11.0.3/themes/src/main/resources/theme/base/login/login.ftl) into [`Login.tsx`](https://github.com/InseeFrLab/keycloakify/blob/main/src/lib/components/Login.tsx).  


To get you started you can read [this section of the readme](https://github.com/InseeFrLab/keycloakify#changing-the-look-and-feel), I just updated the instructions.  

Best regards.
