### ISSUE TITLE
Error when trying to add idp-review-user-profile.ftl

### ISSUE THREAD

**Issue by Romcol** [InseeFrLab/keycloakify#86]
Hi,

I've tried to implement `idp-review-user-profile.ftl` in my keycloakify project (specifing the ftl in extraPages etc.) but the page returns a "Internal Server Error".

Apparently, there's an issue in `ftl_object_to_js_code_declaring_an_object`, as the logs suggest :

`{"refId":2,"exceptionType":"freemarker.core._MiscTemplateException","message":"When calling function \"ftl_object_to_js_code_declaring_an_object\", required parameter \"object\" (parameter #1) was specified, but had null/missing value.\n\n----\nTip: If the parameter value expression on the caller side is known to be legally null/missing, you may want to specify a default value for it with the \"!\" operator, like paramValue!defaultValue.\n----\n\n----\nFTL stack trace (\"~\" means nesting-related):\n\t- Failed at: #function ftl_object_to_js_code_decla...  [in template \"idp-review-user-profile.ftl\" in function \"ftl_object_to_js_code_declaring_an_object\" at line 86, column 1]\n\t- Reached through: ${ftl_object_to_js_code_declaring_an_...  [in template \"idp-review-user-profile.ftl\" at line 7, column 1]\n----","frames":`

Do you have any idea on how we could fix this?

Thanks :pray:

**Comment by garronej** [comment]
Hi,  
This error does surprise me,  
It would help if you could help me reproduce somehow.  
Or maybe you could give remote access to your machine.  

I am currently stuck.  I can't run my own project on my new Macbook M1.

**Comment by Romcol** [comment]
Hi, have you manage to fix your M1 issue?
I would appreciate if you could take a look.
Thanks :pray:

**Comment by garronej** [comment]
Yes, it does work with M1 now.  
Please provide a sample project with a documented reproduction path and I will fix in the better delays.

**Comment by Romcol** [comment]
Hi,

After some keycloak and keycloakify updates the issue has ceased. I think we can close the issue :relieved:

**Comment by redben** [comment]
Sorry to add to a closed issue!
I have been having this problem for the last 4 hours. The issue still occurs when you enable  `--features=declarative-user-profile`. But when disabled declarative-user-profiles everything works fine. I am new to keycloakify and keycloak theming. Anymore info I can provide to help fix this, or directions as to what needs to be changed in keycloakify?

Thank!

**Comment by garronej** [comment]
Hi @redben,  
Are you geting a 500?  
What Keycloakify version are you using?

**Comment by Romcol** [comment]
Hi @redben ,
If it works with keycloak original theme I think you have a similar crashing `.ftl` issue.
The issue emerged again for us in some conditions so I've made a PR [here](https://github.com/InseeFrLab/keycloakify/pull/164) (which has not been accepted yet), to prevent the page from crashing.
You can try adding `<#attempt>` `<#recover>` `</#attempt>` to the generated `.ftl` of your page to see if such PR will fix your problem. Hopefully we can find something that will tackle both of our issues.

**Comment by garronej** [comment]
@Romcol,  
Ok! Nice to know it's releated.  
Sorry for not answering your message on the other issue yet.  
I'm still in vacation but I promise we are going to sort this out!

**Comment by redben** [comment]
> Hi @redben,  
> 
> Are you geting a 500?  
> 
> What Keycloakify version are you using? 

Yes 500, Using Keycloakify 5.9.0 (keycloak 18.0.2)

**Comment by redben** [comment]
Hi @Romcol,
Indeed I saw your PR, maybe my head was hurting too much but it seemed to me what you have in the code is already there in keycloakify. I will look again.


> Hi @redben ,
> 
> If it works with keycloak original theme I think you have a similar crashing `.ftl` issue.
> 
> The issue emerged again for us in some conditions so I've made a PR [here](https://github.com/InseeFrLab/keycloakify/pull/164) (which has not been accepted yet), to prevent the page from crashing.
> 
> You can try adding `<#attempt>` `<#recover>` `</#attempt>` to the generated `.ftl` of your page to see if such PR will fix your problem. Hopefully we can find something that will tackle both of our issues.

**Comment by redben** [comment]
@Romcol @garronej You were right patching using your PR fixed it. Thanks a lot!
