### ISSUE TITLE
Ability to customize emails

### ISSUE THREAD

**Issue by Powersource** [InseeFrLab/keycloakify#9]
Of what I understand this isn't supported yet? Would it be enough [to follow this](https://github.com/InseeFrLab/keycloakify#some-pages-still-have-the-default-theme-why) or would other steps/methods be required?

**Comment by garronej** [comment]
I am not sure I understand what you mean by customising emails?  
Do you mean whitelisting emails domain that are allowed to register? If it's that, [it is supported](https://github.com/InseeFrLab/keycloakify#email-domain-whitelist).
If not what page are you referring to?  
![image](https://user-images.githubusercontent.com/6702424/120111377-0341ab80-c172-11eb-8a83-2c34ac0571a6.png)

**Comment by Powersource** [comment]
I mean the emails that keycloak sends to users when they e.g. sign up and need to verify their email.

**Comment by garronej** [comment]
Ahh yeah of course, I see.

Yes this is probably something that we would like to support in the future but that is out of scope for now.

**Comment by garronej** [comment]
Note, however, that we will never be able to implement the emails in React, we can't bundle JS into emails.  
If I provide a solution il will probably be using [eta](https://eta.js.org)...

**Comment by Powersource** [comment]
Thought about it a bit more. For our usecase we don't yet need full easy theming of the emails, being able to easily replace the "message" files at the same time as loading the rest of the theme would be enough. In our case it's `keycloak/themes/customtheme/email/messages/messages_en.properties`. It would be cool if we could put that in some folder of static files and then it would be inserted by keycloakify in the right location in the jar file :)

**Comment by garronej** [comment]
Agreed,  
I put that in my todo list but i'll encourage you to implement an alternative solution in the meantime as I don't know when I will have the time to implement it.

**Comment by ialisyed** [comment]
Hi @Powersource,

How did you customize emails? Could you please share some insight?

TIA,
Syed

**Comment by abforman** [comment]
I did a hack to shove an `email/` directory into the theme JAR by adding some commands in package.json:
```    
"scripts": {
        "build": "react-scripts build",
        "keycloak": "yarn build && yarn emails && build-keycloak-theme && yarn emails2",
        "emails": "mkdir -p build_keycloak/src/main/resources/theme/THEME_NAME/email; cp -R email build_keycloak/src/main/resources/theme/THEME_NAME/",
        "emails2": "jar -uf ./build_keycloak/target/THEME_NAME-keycloak-theme-VERSION.jar -C . META-INF/keycloak-themes.json",
...
```

Both the `email/` directory hierarchy and the `keycloak-themes.json` are just static files.

The only reason for the keycloak-themes overlay is to add "email" to the array of types so that it will show up as an entry in the drop-down.

**Comment by garronej** [comment]
[It's done](https://github.com/InseeFrLab/keycloakify#email-template-customization)
