### ISSUE TITLE
Transform regex is missing upercase letters

### ISSUE THREAD

**Issue by valkum** [InseeFrLab/keycloakify#90]
Thanks for your work. We currently are evaluating the usage of keycloakify but see some errors.

Currently the transform of resource paths fails because the regex is only using lowercase letters for the replace matching.

Our tooling outputs something like this `Ai=Nt.p+"static/media/start-meeting-ill....` thus the replace only matches `t.p+"static` leading to a replacement to `Nwindow...` which will obviously fail.

If you agree that a simple fix would be to add upper case letters, I can probably offer a patch

**Comment by garronej** [comment]
Hi @valkum,  
It should be fixed now.  ([v4.8.4](https://github.com/InseeFrLab/keycloakify/releases/tag/v4.8.4))
Thanks for reporting.
