### ISSUE TITLE
Migrating theme to 18.0.0 keycloak

### ISSUE THREAD

**Issue by hookenful** [InseeFrLab/keycloakify#93]
Hello there!

We started developing our theme since 17.0.1 version. Yesterday, we tried to migrate to 18.0.0 version, but after this something started behave weird, routes for `resources` were somelike `http://domain/resources/18.0.0/...` and so that obviously was 404.

Does need to rebuilt theme or package changes in Keycloakify for 18.0.0 version?

**Comment by garronej** [comment]
Damnit.  
I havent really validated keyckloak 18 yet.  
It's silly but I can't get it to work, with or without keycloakify.  
Screenshots would help a lot. Reproduction path woud be even better.

**Comment by garronej** [comment]
I have opened an issue to move forward with the Keycloak 18 migration.  
https://github.com/keycloak/keycloak-web/issues/306  

In the meantime, make sure the problem you are experiencing are actually related with Keycloakify.  
Please test with the default theme and see if things works as expected.   

Best regards

**Comment by garronej** [comment]
Hi @hookenful,  
After testing with Keycloak 18 I didn't notice any issue.  
And no, you aren't supposed to need to rebuild the theme to upgrade Keycloak.  
I am closing this but I am here to help if you need any further support.
