### ISSUE TITLE
Build 7x slowers between 4.8.3 and 4.8.4

### ISSUE THREAD

**Issue by Romcol** [InseeFrLab/keycloakify#99]
Hi!

When trying to upgrade keycloakify I noticed that the build is much slower now.
The first version which has made the issue arises is `4.8.4`.

### Timing my project

Version `4.8.3` : 0m28,849s
Version `4.8.4` : 3m35,671s

As we can see here https://github.com/InseeFrLab/keycloakify/compare/v4.8.3...v4.8.4, probably this file `src/bin/build-keycloak-theme/replaceImportFromStatic.ts` is to blame. There are some changes in regexes that may be slower to process.

I have tried on several versions of node (`v16.14.2`, `v12.22.11`, ...) but it is the same.

Do you have any idea?

Thanks :pray:

**Comment by garronej** [comment]
Hi @Romcol,  
Thanks for reporting.  
It must be https://github.com/InseeFrLab/keycloakify/commit/0e194ee045f5710264a676e6dbcc4580a9ecccdb  
related to https://github.com/InseeFrLab/keycloakify/issues/90  

Feel free to submit a PR.

**Comment by Romcol** [comment]
Hi,
Indeed. I made a pull request :)
